//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Default {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Default() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Default", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://behpardazan.com/.
        /// </summary>
        internal static string BehpardazanURL {
            get {
                return ResourceManager.GetString("BehpardazanURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website design of Behpardazan Software Company.
        /// </summary>
        internal static string CompanyBehpardazan {
            get {
                return ResourceManager.GetString("CompanyBehpardazan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/animate/css/animate.min.css.
        /// </summary>
        internal static string CSS_ANIMATECSS {
            get {
                return ResourceManager.GetString("CSS_ANIMATECSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/bootstrap-rtl/css/bootstrap.rtl.css.
        /// </summary>
        internal static string CSS_BOOTSTRAP {
            get {
                return ResourceManager.GetString("CSS_BOOTSTRAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/bootstrap-4/css/bootstrap.min.css.
        /// </summary>
        internal static string CSS_BOOTSTRAP_4 {
            get {
                return ResourceManager.GetString("CSS_BOOTSTRAP_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/bootstrap/css/bootstrap.min.css.
        /// </summary>
        internal static string CSS_BOOTSTRAP_LTR {
            get {
                return ResourceManager.GetString("CSS_BOOTSTRAP_LTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/bootstrap-rtl/css/bootstrap.rtl.css.
        /// </summary>
        internal static string CSS_BOOTSTRAP_RTL {
            get {
                return ResourceManager.GetString("CSS_BOOTSTRAP_RTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/default/css/codeprocess.css.
        /// </summary>
        internal static string CSS_CODEPROCESS {
            get {
                return ResourceManager.GetString("CSS_CODEPROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/default/css/codeprocess.rtl.css.
        /// </summary>
        internal static string CSS_CODEPROCESS_LANGUAGE {
            get {
                return ResourceManager.GetString("CSS_CODEPROCESS_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/font-awesome/css/font-awesome.min.css.
        /// </summary>
        internal static string CSS_FONTAWESOME {
            get {
                return ResourceManager.GetString("CSS_FONTAWESOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/font-awesome-4/css/font-awesome.min.css.
        /// </summary>
        internal static string CSS_FONTAWESOME_4 {
            get {
                return ResourceManager.GetString("CSS_FONTAWESOME_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/frikadell/css/frikadell-font.css.
        /// </summary>
        internal static string CSS_FRIKADELL {
            get {
                return ResourceManager.GetString("CSS_FRIKADELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/ionicons/css/ionicons.min.css.
        /// </summary>
        internal static string CSS_IONICONS {
            get {
                return ResourceManager.GetString("CSS_IONICONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/animated-modal/css/animated-modal.min.css.
        /// </summary>
        internal static string CSS_PLUGIN_ANIMATED_MODAL {
            get {
                return ResourceManager.GetString("CSS_PLUGIN_ANIMATED_MODAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/bootstrap-toggle/css/bootstrap-toggle.min.css.
        /// </summary>
        internal static string CSS_PLUGIN_BOOTSTRAP_TOGGLE {
            get {
                return ResourceManager.GetString("CSS_PLUGIN_BOOTSTRAP_TOGGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/bt-font/css/bt-font.css.
        /// </summary>
        internal static string CSS_PLUGIN_BTFONT {
            get {
                return ResourceManager.GetString("CSS_PLUGIN_BTFONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/crellyslider/css/crellyslider.min.css.
        /// </summary>
        internal static string CSS_PLUGIN_CRELLY {
            get {
                return ResourceManager.GetString("CSS_PLUGIN_CRELLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/fancybox/css/fancybox.min.css.
        /// </summary>
        internal static string CSS_PLUGIN_FANCYBOX {
            get {
                return ResourceManager.GetString("CSS_PLUGIN_FANCYBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/flickity/css/flickity.min.css.
        /// </summary>
        internal static string CSS_PLUGIN_FLICKITY {
            get {
                return ResourceManager.GetString("CSS_PLUGIN_FLICKITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/flipclock-counter/css/flipclock.css.
        /// </summary>
        internal static string CSS_PLUGIN_FLIPCLOCK {
            get {
                return ResourceManager.GetString("CSS_PLUGIN_FLIPCLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/galereya/css/jquery.galereya.css.
        /// </summary>
        internal static string CSS_PLUGIN_GALEREYA {
            get {
                return ResourceManager.GetString("CSS_PLUGIN_GALEREYA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/jquery-ui/css/jquery-ui.css.
        /// </summary>
        internal static string CSS_PLUGIN_JQUERYUI {
            get {
                return ResourceManager.GetString("CSS_PLUGIN_JQUERYUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/jquery-ui-rtl-slider/css/jquery.ui.slider-rtl.css.
        /// </summary>
        internal static string CSS_PLUGIN_JQUERYUI_RTL_SLIDER {
            get {
                return ResourceManager.GetString("CSS_PLUGIN_JQUERYUI_RTL_SLIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/lightbox/css/lightbox.css.
        /// </summary>
        internal static string CSS_PLUGIN_LIGHTBOX {
            get {
                return ResourceManager.GetString("CSS_PLUGIN_LIGHTBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/light-slider/css/lightslider.css.
        /// </summary>
        internal static string CSS_PLUGIN_LIGHTSLIDER {
            get {
                return ResourceManager.GetString("CSS_PLUGIN_LIGHTSLIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/material/css/material.min.css.
        /// </summary>
        internal static string CSS_PLUGIN_MATERIAL {
            get {
                return ResourceManager.GetString("CSS_PLUGIN_MATERIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/nouislider/css/nouislider.min.css.
        /// </summary>
        internal static string CSS_PLUGIN_NOUISLIDER {
            get {
                return ResourceManager.GetString("CSS_PLUGIN_NOUISLIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/owl-carousel/css/owl.carousel.css.
        /// </summary>
        internal static string CSS_PLUGIN_OWLCAROUSEL {
            get {
                return ResourceManager.GetString("CSS_PLUGIN_OWLCAROUSEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/owl-carousel/css/owl.theme.css.
        /// </summary>
        internal static string CSS_PLUGIN_OWLCAROUSEL_THEME {
            get {
                return ResourceManager.GetString("CSS_PLUGIN_OWLCAROUSEL_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/owl-carousel-v2/css/owl.theme.default.css.
        /// </summary>
        internal static string CSS_PLUGIN_OWLCAROUSEL_THEME_V2 {
            get {
                return ResourceManager.GetString("CSS_PLUGIN_OWLCAROUSEL_THEME_V2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/owl-carousel-v2/css/owl.carousel.min.css.
        /// </summary>
        internal static string CSS_PLUGIN_OWLCAROUSEL_V2 {
            get {
                return ResourceManager.GetString("CSS_PLUGIN_OWLCAROUSEL_V2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/resposnsive-slides/css/responsiveslides.css.
        /// </summary>
        internal static string CSS_PLUGIN_RESPONSIVE_SLIDES {
            get {
                return ResourceManager.GetString("CSS_PLUGIN_RESPONSIVE_SLIDES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/revolution-slider/css/setting.css.
        /// </summary>
        internal static string CSS_PLUGIN_REVOLUTION_SLIDER_SETTING {
            get {
                return ResourceManager.GetString("CSS_PLUGIN_REVOLUTION_SLIDER_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/salvattore/css/salvattore.css.
        /// </summary>
        internal static string CSS_PLUGIN_SALVATTORE {
            get {
                return ResourceManager.GetString("CSS_PLUGIN_SALVATTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/sequence/css/sequence-theme.modern-slide-in.css.
        /// </summary>
        internal static string CSS_PLUGIN_SEQUENCE {
            get {
                return ResourceManager.GetString("CSS_PLUGIN_SEQUENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/jquery-simplelens/css/jquery.simpleLens.css.
        /// </summary>
        internal static string CSS_PLUGIN_SIMPLELENS {
            get {
                return ResourceManager.GetString("CSS_PLUGIN_SIMPLELENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/slick-slider/css/slick.css.
        /// </summary>
        internal static string CSS_PLUGIN_SLICK {
            get {
                return ResourceManager.GetString("CSS_PLUGIN_SLICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/slick-slider/css/slick-theme.css.
        /// </summary>
        internal static string CSS_PLUGIN_SLICKTHEME {
            get {
                return ResourceManager.GetString("CSS_PLUGIN_SLICKTHEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/jquery-smartmenus/css/jquery.smartmenus.bootstrap.css.
        /// </summary>
        internal static string CSS_PLUGIN_SMARTMENU {
            get {
                return ResourceManager.GetString("CSS_PLUGIN_SMARTMENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/toastr/css/toastr.min.css.
        /// </summary>
        internal static string CSS_PLUGIN_TOASTR {
            get {
                return ResourceManager.GetString("CSS_PLUGIN_TOASTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/unslider/js/unslider-min.css.
        /// </summary>
        internal static string CSS_PLUGIN_UNSLIDER {
            get {
                return ResourceManager.GetString("CSS_PLUGIN_UNSLIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/Plugins/zuck/css/zuck.css.
        /// </summary>
        internal static string CSS_PLUGIN_ZUCK {
            get {
                return ResourceManager.GetString("CSS_PLUGIN_ZUCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/Plugins/zuck/css/snapgram.css.
        /// </summary>
        internal static string CSS_PLUGIN_ZUCK_SNAPGRAM {
            get {
                return ResourceManager.GetString("CSS_PLUGIN_ZUCK_SNAPGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/default/css/StarRate.css.
        /// </summary>
        internal static string CSS_STAR_RATE {
            get {
                return ResourceManager.GetString("CSS_STAR_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DISCOUNT {
            get {
                return ResourceManager.GetString("DISCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/default/image/locations-banner.png.
        /// </summary>
        internal static string IMAGE_ADDRESS_BANNER {
            get {
                return ResourceManager.GetString("IMAGE_ADDRESS_BANNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/default/image/empty-avatar.png.
        /// </summary>
        internal static string IMAGE_EMPTY_AVATAR {
            get {
                return ResourceManager.GetString("IMAGE_EMPTY_AVATAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/bootstrap/js/bootstrap.min.js.
        /// </summary>
        internal static string JS_BOOTSTRAP {
            get {
                return ResourceManager.GetString("JS_BOOTSTRAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/bootstrap-4/js/bootstrap.min.js.
        /// </summary>
        internal static string JS_BOOTSTRAP_4 {
            get {
                return ResourceManager.GetString("JS_BOOTSTRAP_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/bootstrap-rtl/js/bootstrap.rtl.js.
        /// </summary>
        internal static string JS_BOOTSTRAP_RTL {
            get {
                return ResourceManager.GetString("JS_BOOTSTRAP_RTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/default/js/codeprocess.ajax.js.
        /// </summary>
        internal static string JS_CODEPROCESS_AJAX {
            get {
                return ResourceManager.GetString("JS_CODEPROCESS_AJAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/default/js/codeprocess.js.
        /// </summary>
        internal static string JS_CODEPROCESS_CORE {
            get {
                return ResourceManager.GetString("JS_CODEPROCESS_CORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/default/js/codeprocess.datetime.js.
        /// </summary>
        internal static string JS_CODEPROCESS_DATETIME {
            get {
                return ResourceManager.GetString("JS_CODEPROCESS_DATETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/default/js/codeprocess.language.js.
        /// </summary>
        internal static string JS_CODEPROCESS_LANGUAGE {
            get {
                return ResourceManager.GetString("JS_CODEPROCESS_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/jquery/js/jquery.min.js.
        /// </summary>
        internal static string JS_JQUERY {
            get {
                return ResourceManager.GetString("JS_JQUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/animated-modal/js/animated-modal.min.js.
        /// </summary>
        internal static string JS_PLUGIN_ANIMATED_MODAL {
            get {
                return ResourceManager.GetString("JS_PLUGIN_ANIMATED_MODAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/jquery-autocomplete/js/jquery.autocomplete.min.js.
        /// </summary>
        internal static string JS_PLUGIN_AUTOCOMPLETE {
            get {
                return ResourceManager.GetString("JS_PLUGIN_AUTOCOMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/bootstrap-toggle/js/bootstrap-toggle.min.js.
        /// </summary>
        internal static string JS_PLUGIN_BOOTSTRAP_TOGGLE {
            get {
                return ResourceManager.GetString("JS_PLUGIN_BOOTSTRAP_TOGGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/breaking-news/js/breakingNews.js.
        /// </summary>
        internal static string JS_PLUGIN_BREAKINGNEWS {
            get {
                return ResourceManager.GetString("JS_PLUGIN_BREAKINGNEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/classie/js/classie.js.
        /// </summary>
        internal static string JS_PLUGIN_CLASSIE {
            get {
                return ResourceManager.GetString("JS_PLUGIN_CLASSIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/color-thief/js/color-thief.min.js.
        /// </summary>
        internal static string JS_PLUGIN_COLORTHIEF {
            get {
                return ResourceManager.GetString("JS_PLUGIN_COLORTHIEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/crellyslider/js/jquery.crellyslider.min.js.
        /// </summary>
        internal static string JS_PLUGIN_CRELLY {
            get {
                return ResourceManager.GetString("JS_PLUGIN_CRELLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/custom-scrollbar/js/mCustomScrollbar.min.js.
        /// </summary>
        internal static string JS_PLUGIN_CUSTOM_SCROLLBAR {
            get {
                return ResourceManager.GetString("JS_PLUGIN_CUSTOM_SCROLLBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/fancybox/js/fancybox.min.js.
        /// </summary>
        internal static string JS_PLUGIN_FANCYBOX {
            get {
                return ResourceManager.GetString("JS_PLUGIN_FANCYBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/flexslider/js/jquery.flexslider.js.
        /// </summary>
        internal static string JS_PLUGIN_FLEXSLIDER {
            get {
                return ResourceManager.GetString("JS_PLUGIN_FLEXSLIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/flickity/js/flickity.pkgd.min.js.
        /// </summary>
        internal static string JS_PLUGIN_FLICKITY {
            get {
                return ResourceManager.GetString("JS_PLUGIN_FLICKITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/flipclock-counter/js/flipclock.js.
        /// </summary>
        internal static string JS_PLUGIN_FLIPCLOCK {
            get {
                return ResourceManager.GetString("JS_PLUGIN_FLIPCLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/galereya/js/jquery.galereya.min.js.
        /// </summary>
        internal static string JS_PLUGIN_GALEREYA {
            get {
                return ResourceManager.GetString("JS_PLUGIN_GALEREYA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/recaptcha/api.js.
        /// </summary>
        internal static string JS_PLUGIN_GOOGLE_RECAPTCHA {
            get {
                return ResourceManager.GetString("JS_PLUGIN_GOOGLE_RECAPTCHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/highlight/js/highlight.js.
        /// </summary>
        internal static string JS_PLUGIN_HIGHLIGHT {
            get {
                return ResourceManager.GetString("JS_PLUGIN_HIGHLIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/images-loaded/js/imagesloaded.min.js.
        /// </summary>
        internal static string JS_PLUGIN_IMAGE_LOADED {
            get {
                return ResourceManager.GetString("JS_PLUGIN_IMAGE_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/ion-range-slider/js/ion-range-slider.js.
        /// </summary>
        internal static string JS_PLUGIN_ION_RANGE_SLIDER {
            get {
                return ResourceManager.GetString("JS_PLUGIN_ION_RANGE_SLIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/isotope/js/jquery.isotope.js.
        /// </summary>
        internal static string JS_PLUGIN_ISOTOPE {
            get {
                return ResourceManager.GetString("JS_PLUGIN_ISOTOPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/jquery-ui/js/jquery-ui.js.
        /// </summary>
        internal static string JS_PLUGIN_JQUERYUI {
            get {
                return ResourceManager.GetString("JS_PLUGIN_JQUERYUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/jquery-ui-rtl-slider/js/jquery.ui.slider-rtl.js.
        /// </summary>
        internal static string JS_PLUGIN_JQUERYUI_RTL_SLIDER {
            get {
                return ResourceManager.GetString("JS_PLUGIN_JQUERYUI_RTL_SLIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/jquery-easing/js/jquery.easing.1.3.js.
        /// </summary>
        internal static string JS_PLUGIN_JQUERY_EASING {
            get {
                return ResourceManager.GetString("JS_PLUGIN_JQUERY_EASING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/jquery-migrate/js/jquery-migrate.min.js.
        /// </summary>
        internal static string JS_PLUGIN_JQUERY_MIGRATE {
            get {
                return ResourceManager.GetString("JS_PLUGIN_JQUERY_MIGRATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/jscrollpane/js/jquery.jscrollpane.min.js.
        /// </summary>
        internal static string JS_PLUGIN_JSCROLLPANE {
            get {
                return ResourceManager.GetString("JS_PLUGIN_JSCROLLPANE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/knockout/knockout-3.4.2.js.
        /// </summary>
        internal static string JS_PLUGIN_KNOCKOUT {
            get {
                return ResourceManager.GetString("JS_PLUGIN_KNOCKOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/lightbox/js/lightbox.js.
        /// </summary>
        internal static string JS_PLUGIN_LIGHTBOX {
            get {
                return ResourceManager.GetString("JS_PLUGIN_LIGHTBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/light-slider/js/lightslider.js.
        /// </summary>
        internal static string JS_PLUGIN_LIGHTSLIDER {
            get {
                return ResourceManager.GetString("JS_PLUGIN_LIGHTSLIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/masonry/js/masonry.min.js.
        /// </summary>
        internal static string JS_PLUGIN_MASONRY {
            get {
                return ResourceManager.GetString("JS_PLUGIN_MASONRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/material/js/material.min.js.
        /// </summary>
        internal static string JS_PLUGIN_MATERIAL {
            get {
                return ResourceManager.GetString("JS_PLUGIN_MATERIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/modal-effects/js/modalEffects.js.
        /// </summary>
        internal static string JS_PLUGIN_MODAL_EFFECTS {
            get {
                return ResourceManager.GetString("JS_PLUGIN_MODAL_EFFECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/mousewheel/js/jquery.mousewheel.js.
        /// </summary>
        internal static string JS_PLUGIN_MOUSEWHEEL {
            get {
                return ResourceManager.GetString("JS_PLUGIN_MOUSEWHEEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/nouislider/js/nouislider.min.js.
        /// </summary>
        internal static string JS_PLUGIN_NOUISLIDER {
            get {
                return ResourceManager.GetString("JS_PLUGIN_NOUISLIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.onesignal.com/sdks/OneSignalSDK.js.
        /// </summary>
        internal static string JS_PLUGIN_ONESIGNAL {
            get {
                return ResourceManager.GetString("JS_PLUGIN_ONESIGNAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/owl-carousel/js/owl.carousel.js.
        /// </summary>
        internal static string JS_PLUGIN_OWLCAROUSEL {
            get {
                return ResourceManager.GetString("JS_PLUGIN_OWLCAROUSEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/owl-carousel-v2/js/owl.carousel.min.js.
        /// </summary>
        internal static string JS_PLUGIN_OWLCAROUSEL_V2 {
            get {
                return ResourceManager.GetString("JS_PLUGIN_OWLCAROUSEL_V2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/resposnsive-slides/js/responsiveslides.min.js.
        /// </summary>
        internal static string JS_PLUGIN_RESPONSIVE_SLIDES {
            get {
                return ResourceManager.GetString("JS_PLUGIN_RESPONSIVE_SLIDES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/revolution-slider/js/revolution.extension.actions.min.js.
        /// </summary>
        internal static string JS_PLUGIN_REVOLUTION_ACTIONS {
            get {
                return ResourceManager.GetString("JS_PLUGIN_REVOLUTION_ACTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/revolution-slider/js/revolution.extension.layeranimation.min.js.
        /// </summary>
        internal static string JS_PLUGIN_REVOLUTION_LAYERANIMATION {
            get {
                return ResourceManager.GetString("JS_PLUGIN_REVOLUTION_LAYERANIMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/revolution-slider/js/revolution.extension.navigation.min.js.
        /// </summary>
        internal static string JS_PLUGIN_REVOLUTION_NAVIGATION {
            get {
                return ResourceManager.GetString("JS_PLUGIN_REVOLUTION_NAVIGATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/revolution-slider/js/revolution.extension.slideanims.min.js.
        /// </summary>
        internal static string JS_PLUGIN_REVOLUTION_SLIDEANIMS {
            get {
                return ResourceManager.GetString("JS_PLUGIN_REVOLUTION_SLIDEANIMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/revolution-slider/js/jquery.themepunch.revolution.min.js.
        /// </summary>
        internal static string JS_PLUGIN_REVOLUTION_THEMEPUNCH {
            get {
                return ResourceManager.GetString("JS_PLUGIN_REVOLUTION_THEMEPUNCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/revolution-slider/js/jquery.themepunch.tools.min.js.
        /// </summary>
        internal static string JS_PLUGIN_REVOLUTION_THEMEPUNCH_TOOLS {
            get {
                return ResourceManager.GetString("JS_PLUGIN_REVOLUTION_THEMEPUNCH_TOOLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/salvattore/js/salvattore.js.
        /// </summary>
        internal static string JS_PLUGIN_SALVATTORE {
            get {
                return ResourceManager.GetString("JS_PLUGIN_SALVATTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/jquery-scrollbar/js/jquery.scrollbox.min.js.
        /// </summary>
        internal static string JS_PLUGIN_SCROLLBAR {
            get {
                return ResourceManager.GetString("JS_PLUGIN_SCROLLBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/sequence/js/sequence.js.
        /// </summary>
        internal static string JS_PLUGIN_SEQUENCE {
            get {
                return ResourceManager.GetString("JS_PLUGIN_SEQUENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/sequence/js/sequence-theme.modern-slide-in.js.
        /// </summary>
        internal static string JS_PLUGIN_SEQUENCE_THEME_MODERN {
            get {
                return ResourceManager.GetString("JS_PLUGIN_SEQUENCE_THEME_MODERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/jquery-simplelens/js/jquery.simpleLens.js.
        /// </summary>
        internal static string JS_PLUGIN_SIMPLELENS {
            get {
                return ResourceManager.GetString("JS_PLUGIN_SIMPLELENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/jquery-simplelens/js/jquery.simpleGallery.js.
        /// </summary>
        internal static string JS_PLUGIN_SIMPLELENS_GALLERY {
            get {
                return ResourceManager.GetString("JS_PLUGIN_SIMPLELENS_GALLERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/slick-slider/js/slick.min.js.
        /// </summary>
        internal static string JS_PLUGIN_SLICK {
            get {
                return ResourceManager.GetString("JS_PLUGIN_SLICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/slick-nav/js/slicknav.min.js.
        /// </summary>
        internal static string JS_PLUGIN_SLICKNAV {
            get {
                return ResourceManager.GetString("JS_PLUGIN_SLICKNAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/jquery-smartmenus/js/jquery.smartmenus.js.
        /// </summary>
        internal static string JS_PLUGIN_SMARTMENU {
            get {
                return ResourceManager.GetString("JS_PLUGIN_SMARTMENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/jquery-smartmenus/js/jquery.smartmenus.bootstrap.js.
        /// </summary>
        internal static string JS_PLUGIN_SMARTMENU_BOOTSTRAP {
            get {
                return ResourceManager.GetString("JS_PLUGIN_SMARTMENU_BOOTSTRAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/super-scroll-orama/js/jquery.superscrollorama.js.
        /// </summary>
        internal static string JS_PLUGIN_SUPERSCROLLORAMA {
            get {
                return ResourceManager.GetString("JS_PLUGIN_SUPERSCROLLORAMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/super-scroll-orama/js/tweenmax.min.js.
        /// </summary>
        internal static string JS_PLUGIN_SUPERSCROLLORAMA_TWEENMAX {
            get {
                return ResourceManager.GetString("JS_PLUGIN_SUPERSCROLLORAMA_TWEENMAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/toastr/js/toastr.min.js.
        /// </summary>
        internal static string JS_PLUGIN_TOASTR {
            get {
                return ResourceManager.GetString("JS_PLUGIN_TOASTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/typed/js/typed.js.
        /// </summary>
        internal static string JS_PLUGIN_TYPED {
            get {
                return ResourceManager.GetString("JS_PLUGIN_TYPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/unslider/js/unslider-min.js.
        /// </summary>
        internal static string JS_PLUGIN_UNSLIDER {
            get {
                return ResourceManager.GetString("JS_PLUGIN_UNSLIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/wnumb/js/wnumb.js.
        /// </summary>
        internal static string JS_PLUGIN_WNUMB {
            get {
                return ResourceManager.GetString("JS_PLUGIN_WNUMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/plugins/zoom-sl/js/zoomsl-3.0.min.js.
        /// </summary>
        internal static string JS_PLUGIN_ZOOM {
            get {
                return ResourceManager.GetString("JS_PLUGIN_ZOOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/Plugins/zuck/js/zuck.js.
        /// </summary>
        internal static string JS_PLUGIN_ZUCK {
            get {
                return ResourceManager.GetString("JS_PLUGIN_ZUCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Default/Payment/Merchant.cshtml.
        /// </summary>
        internal static string PARTIAL_MERCHANT {
            get {
                return ResourceManager.GetString("PARTIAL_MERCHANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Default/Partial/Message.cshtml.
        /// </summary>
        internal static string PARTIAL_MESSAGE {
            get {
                return ResourceManager.GetString("PARTIAL_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Default/Partial/SeoPack.cshtml.
        /// </summary>
        internal static string PARTIAL_SEOPACK {
            get {
                return ResourceManager.GetString("PARTIAL_SEOPACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Areas/Store/Views/Shared/_Layout.cshtml.
        /// </summary>
        internal static string STORE_LAYOUT {
            get {
                return ResourceManager.GetString("STORE_LAYOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Areas/Store/Views/Shared/_Layout_Blank.cshtml.
        /// </summary>
        internal static string STORE_LAYOUT_BLANK {
            get {
                return ResourceManager.GetString("STORE_LAYOUT_BLANK", resourceCulture);
            }
        }
    }
}
