//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Zeno {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Zeno() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Zeno", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Zeno/Css/fontawesom.css.
        /// </summary>
        internal static string CSS_ {
            get {
                return ResourceManager.GetString("CSS_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Zeno/Css/animate.css.
        /// </summary>
        internal static string CSS_ANIMATE {
            get {
                return ResourceManager.GetString("CSS_ANIMATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Zeno/Css/bootstrap-icons.css.
        /// </summary>
        internal static string CSS_BOOTSTRAP_ICON {
            get {
                return ResourceManager.GetString("CSS_BOOTSTRAP_ICON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Zeno/Css/bootstrap.min.css.
        /// </summary>
        internal static string CSS_BOOTSTRAP_MIN {
            get {
                return ResourceManager.GetString("CSS_BOOTSTRAP_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Zeno/Css/hover.css.
        /// </summary>
        internal static string CSS_HOVER {
            get {
                return ResourceManager.GetString("CSS_HOVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Zeno/Css/magiczoomplus.css.
        /// </summary>
        internal static string CSS_MAGIC {
            get {
                return ResourceManager.GetString("CSS_MAGIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Zeno/Css/owl.carousel.min.css.
        /// </summary>
        internal static string CSS_OWL_CAROUSEL {
            get {
                return ResourceManager.GetString("CSS_OWL_CAROUSEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Zeno/Css/owl.theme.default.min.css.
        /// </summary>
        internal static string CSS_OWL_CAROUSEL_THEME {
            get {
                return ResourceManager.GetString("CSS_OWL_CAROUSEL_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Zeno/Css/ion.rangeSlider.min.css.
        /// </summary>
        internal static string CSS_RANGE {
            get {
                return ResourceManager.GetString("CSS_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Zeno/Css/style.css.
        /// </summary>
        internal static string CSS_STYLE {
            get {
                return ResourceManager.GetString("CSS_STYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Zeno/Js/bootstrap.bundle.min.js.
        /// </summary>
        internal static string JS_BOOTSTRAP_BUNDLE {
            get {
                return ResourceManager.GetString("JS_BOOTSTRAP_BUNDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Zeno/Js/jquery.js.
        /// </summary>
        internal static string JS_JQUERY {
            get {
                return ResourceManager.GetString("JS_JQUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Zeno/Js/magiczoomplus.js.
        /// </summary>
        internal static string JS_MAGIC {
            get {
                return ResourceManager.GetString("JS_MAGIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Zeno/Js/owl.carousel.min.js.
        /// </summary>
        internal static string JS_OWL_CAROUSEL {
            get {
                return ResourceManager.GetString("JS_OWL_CAROUSEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Zeno/Js/ion.rangeSlider.min.js.
        /// </summary>
        internal static string JS_RANGE_SLIDER {
            get {
                return ResourceManager.GetString("JS_RANGE_SLIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Plugins/toastr/js/toastr.min.js.
        /// </summary>
        internal static string JS_TOASTR {
            get {
                return ResourceManager.GetString("JS_TOASTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Zeno/Js/scripts.js.
        /// </summary>
        internal static string JS_WEBSITE {
            get {
                return ResourceManager.GetString("JS_WEBSITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Zeno/Js/Zeno_JavaScript.js.
        /// </summary>
        internal static string JS_ZENO {
            get {
                return ResourceManager.GetString("JS_ZENO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Zeno/Shared/_UserLayout.cshtml.
        /// </summary>
        internal static string USER_LAYOUT {
            get {
                return ResourceManager.GetString("USER_LAYOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Zeno/Shared/_Layout.cshtml.
        /// </summary>
        internal static string WEBSITE_LAYOUT {
            get {
                return ResourceManager.GetString("WEBSITE_LAYOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Zeno/Shared/_LayoutIndex.cshtml.
        /// </summary>
        internal static string WEBSITE_LAYOUTIndex {
            get {
                return ResourceManager.GetString("WEBSITE_LAYOUTIndex", resourceCulture);
            }
        }
    }
}
