//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.AccountAddress = new HashSet<AccountAddress>();
            this.AccountBasket = new HashSet<AccountBasket>();
            this.AccountCredit = new HashSet<AccountCredit>();
            this.AccountDocument = new HashSet<AccountDocument>();
            this.AccountLog = new HashSet<AccountLog>();
            this.AccountLogVisit = new HashSet<AccountLogVisit>();
            this.AccountOrder = new HashSet<AccountOrder>();
            this.AccountPasswordForget = new HashSet<AccountPasswordForget>();
            this.AccountReagent = new HashSet<AccountReagent>();
            this.Payment = new HashSet<Payment>();
            this.PostLike = new HashSet<PostLike>();
            this.ProductComment = new HashSet<ProductComment>();
            this.ProductLike = new HashSet<ProductLike>();
            this.ProductNotify = new HashSet<ProductNotify>();
            this.ProductVisit = new HashSet<ProductVisit>();
            this.ShopChat = new HashSet<ShopChat>();
            this.ShopFollow = new HashSet<ShopFollow>();
            this.ShopReportBlock = new HashSet<ShopReportBlock>();
            this.Store = new HashSet<Store>();
            this.StoreComment = new HashSet<StoreComment>();
            this.SurveyAnswer = new HashSet<SurveyAnswer>();
            this.TelegramAccount = new HashSet<TelegramAccount>();
            this.WebsiteContactForm = new HashSet<WebsiteContactForm>();
            this.WebsiteFormAccount = new HashSet<WebsiteFormAccount>();
            this.WebsiteFormValue = new HashSet<WebsiteFormValue>();
            this.AccountReport = new HashSet<AccountReport>();
            this.Question = new HashSet<Question>();
            this.ShippingSubscriptionPayment = new HashSet<ShippingSubscriptionPayment>();
            this.CreditShoping = new HashSet<CreditShoping>();
            this.Product = new HashSet<Product>();
            this.LadderPayment = new HashSet<LadderPayment>();
            this.SmartOfferVisit = new HashSet<SmartOfferVisit>();
        }
    
        public int ID { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> PictureId { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string NationalCode { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Job { get; set; }
        public string Company { get; set; }
        public string CompanyNo { get; set; }
        public string ReagentName { get; set; }
        public string Agent { get; set; }
        public string AgentPhone { get; set; }
        public string Description { get; set; }
        public System.Guid UniqueId { get; set; }
        public Nullable<bool> IsMale { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public string ReagentCode { get; set; }
        public Nullable<int> ReagentId { get; set; }
        public Nullable<System.DateTime> SyncDatetime { get; set; }
        public string SyncId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string UserName { get; set; }
        public string Website { get; set; }
        public string Fax { get; set; }
        public string Instagram { get; set; }
        public string Telegram { get; set; }
        public string WhatsApp { get; set; }
        public string ProfileUrl { get; set; }
        public Nullable<long> Lat { get; set; }
        public Nullable<long> Long { get; set; }
        public bool ChangeUserName { get; set; }
        public string Linkedin { get; set; }
        public string Facebook { get; set; }
        public string Profession { get; set; }
        public string AboutMe { get; set; }
        public string FavoritTitle { get; set; }
        public string FavoritLink { get; set; }
        public bool Deleted { get; set; }
        public string CardNumber { get; set; }
        public string Sheba { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<bool> IsOffice { get; set; }
        public string FatherName { get; set; }
        public Nullable<bool> Verify { get; set; }
        public string VerifyToken { get; set; }
        public Nullable<System.DateTime> ShippingSubscriptionPaymentDate { get; set; }
        public Nullable<bool> ShippingSubscriptionPaymentActive { get; set; }
        public Nullable<bool> IsCreditShopingActive { get; set; }
        public string UserId { get; set; }
        public Nullable<int> FileId { get; set; }
    
        public virtual City City { get; set; }
        public virtual Code Code { get; set; }
        public virtual Country Country { get; set; }
        public virtual Picture Picture { get; set; }
        public virtual State State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountAddress> AccountAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountBasket> AccountBasket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountCredit> AccountCredit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountDocument> AccountDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountLog> AccountLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountLogVisit> AccountLogVisit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountOrder> AccountOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountPasswordForget> AccountPasswordForget { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountReagent> AccountReagent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostLike> PostLike { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductComment> ProductComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductLike> ProductLike { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductNotify> ProductNotify { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductVisit> ProductVisit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopChat> ShopChat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopFollow> ShopFollow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopReportBlock> ShopReportBlock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Store> Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreComment> StoreComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyAnswer> SurveyAnswer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TelegramAccount> TelegramAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebsiteContactForm> WebsiteContactForm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebsiteFormAccount> WebsiteFormAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebsiteFormValue> WebsiteFormValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountReport> AccountReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShippingSubscriptionPayment> ShippingSubscriptionPayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditShoping> CreditShoping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LadderPayment> LadderPayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SmartOfferVisit> SmartOfferVisit { get; set; }
    }
}
