//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountLogVisit
    {
        public int ID { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<int> PageName { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
