//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactUs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContactUs()
        {
            this.ContactUsField = new HashSet<ContactUsField>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<bool> Traceable { get; set; }
        public string TrackingCode { get; set; }
        public string Answer { get; set; }
        public string SendEmail { get; set; }
        public Nullable<int> PictureId { get; set; }
        public Nullable<int> DocumentId { get; set; }
    
        public virtual Picture Picture { get; set; }
        public virtual WebsiteDocument WebsiteDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactUsField> ContactUsField { get; set; }
    }
}
