//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditShoping
    {
        public int ID { get; set; }
        public int AccountId { get; set; }
        public string FullName { get; set; }
        public string Post { get; set; }
        public Nullable<bool> Tenant { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public Nullable<int> Area { get; set; }
        public string Type { get; set; }
        public Nullable<double> AvregeBuy { get; set; }
        public string CompanyId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ActiveDate { get; set; }
        public string AvregeBuy2 { get; set; }
        public string Area2 { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
