//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailSetting
    {
        public int ID { get; set; }
        public int AddressId { get; set; }
        public int EmailTypeId { get; set; }
    
        public virtual EmailAddress EmailAddress { get; set; }
        public virtual EmailType EmailType { get; set; }
    }
}
