//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gallery()
        {
            this.Menu = new HashSet<Menu>();
            this.GalleryLanguage = new HashSet<GalleryLanguage>();
            this.GalleryPictures = new HashSet<GalleryPictures>();
        }
    
        public int ID { get; set; }
        public Nullable<int> WebsiteId { get; set; }
        public string Name { get; set; }
        public Nullable<int> ShowNumber { get; set; }
        public Nullable<System.DateTime> ShowDateTime { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public bool Active { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu> Menu { get; set; }
        public virtual Website Website { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GalleryLanguage> GalleryLanguage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GalleryPictures> GalleryPictures { get; set; }
    }
}
