//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LadderPayment
    {
        public int ID { get; set; }
        public Nullable<int> AccountId { get; set; }
        public int StatusId { get; set; }
        public int MerchantId { get; set; }
        public string RefNumber { get; set; }
        public string ExternalInfo1 { get; set; }
        public string ExternalInfo2 { get; set; }
        public string ExternalInfo3 { get; set; }
        public string ExternalInfo4 { get; set; }
        public Nullable<double> Amount { get; set; }
        public string IpAddress { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public string Description { get; set; }
        public string Sign { get; set; }
        public Nullable<int> PaymentWebsiteId { get; set; }
        public Nullable<int> CurrencyTypeId { get; set; }
        public string ExternalInfo5 { get; set; }
        public string ExternalInfo6 { get; set; }
        public string ExternalInfo7 { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> LedderSettingId { get; set; }
        public Nullable<bool> IsMoblie { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Code Code { get; set; }
        public virtual LadderSetting LadderSetting { get; set; }
        public virtual Merchant Merchant { get; set; }
        public virtual Product Product { get; set; }
    }
}
