//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mall
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mall()
        {
            this.MallContact = new HashSet<MallContact>();
            this.MallPicture = new HashSet<MallPicture>();
            this.Shop = new HashSet<Shop>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> PictureId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string StartBuildingDate { get; set; }
        public string EndBuildingDate { get; set; }
        public string OpeningDate { get; set; }
        public string Owner { get; set; }
        public string Area { get; set; }
        public string ArchitecturalCompany { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public Nullable<int> VisitCount { get; set; }
    
        public virtual City City { get; set; }
        public virtual Picture Picture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MallContact> MallContact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MallPicture> MallPicture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop> Shop { get; set; }
    }
}
