//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductCategory()
        {
            this.Discount = new HashSet<Discount>();
            this.Product = new HashSet<Product>();
            this.ProductCategoryLanguage = new HashSet<ProductCategoryLanguage>();
            this.ProductCustomField = new HashSet<ProductCustomField>();
            this.ProductSubCategory = new HashSet<ProductSubCategory>();
            this.Rebate = new HashSet<Rebate>();
            this.WebsiteFormField = new HashSet<WebsiteFormField>();
            this.ProductsCategory = new HashSet<ProductsCategory>();
            this.QuestionProductCategory = new HashSet<QuestionProductCategory>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Priority { get; set; }
        public int TypeId { get; set; }
        public string SyncId { get; set; }
        public Nullable<int> PictureId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public Nullable<System.DateTime> SyncDatetime { get; set; }
        public Nullable<int> IconId { get; set; }
        public string Url { get; set; }
        public string DescriptionMeta { get; set; }
        public string TitlePage { get; set; }
        public string H1 { get; set; }
        public string Description { get; set; }
        public string CustomLabel { get; set; }
        public bool Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string MetaDescription { get; set; }
        public string RobotMeta { get; set; }
        public string Canonical { get; set; }
        public string Body { get; set; }
        public string Schema { get; set; }
        public bool NoFollow { get; set; }
        public bool NoIndex { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discount> Discount { get; set; }
        public virtual Picture Picture { get; set; }
        public virtual Picture Picture1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
        public virtual ProductCategory ProductCategory1 { get; set; }
        public virtual ProductCategory ProductCategory2 { get; set; }
        public virtual ProductCategory ProductCategory11 { get; set; }
        public virtual ProductCategory ProductCategory3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCategoryLanguage> ProductCategoryLanguage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCustomField> ProductCustomField { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSubCategory> ProductSubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rebate> Rebate { get; set; }
        public virtual ProductType ProductType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebsiteFormField> WebsiteFormField { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsCategory> ProductsCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionProductCategory> QuestionProductCategory { get; set; }
    }
}
