//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductQuantity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductQuantity()
        {
            this.StoreProductQuantity = new HashSet<StoreProductQuantity>();
        }
    
        public int ID { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> ColorId { get; set; }
        public Nullable<int> SizeId { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<double> Price { get; set; }
        public string SyncId { get; set; }
        public Nullable<System.DateTime> SyncDatetime { get; set; }
        public Nullable<System.DateTime> SyncQuantityDatetime { get; set; }
        public Nullable<int> OptionItemId { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProductOptionItem ProductOptionItem { get; set; }
        public virtual Size Size { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreProductQuantity> StoreProductQuantity { get; set; }
    }
}
