//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCustomItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductCustomItem()
        {
            this.ProductCustomItemLanguage = new HashSet<ProductCustomItemLanguage>();
            this.ProductCustomValue = new HashSet<ProductCustomValue>();
        }
    
        public int ID { get; set; }
        public int FieldId { get; set; }
        public string SyncId { get; set; }
        public string Value { get; set; }
        public Nullable<System.DateTime> SyncDatetime { get; set; }
    
        public virtual ProductCustomField ProductCustomField { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCustomItemLanguage> ProductCustomItemLanguage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCustomValue> ProductCustomValue { get; set; }
    }
}
