//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOption
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductOption()
        {
            this.Product = new HashSet<Product>();
            this.ProductOptionItem = new HashSet<ProductOptionItem>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public string Name { get; set; }
        public Nullable<int> ShowNumber { get; set; }
        public string SyncId { get; set; }
        public string SyncName { get; set; }
        public Nullable<System.DateTime> SyncDatetime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOptionItem> ProductOptionItem { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
