//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCustomField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductCustomField()
        {
            this.ProductCustomFieldLanguage = new HashSet<ProductCustomFieldLanguage>();
            this.ProductCustomItem = new HashSet<ProductCustomItem>();
            this.ProductCustomValue = new HashSet<ProductCustomValue>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public Nullable<int> ProductSubCategoryId { get; set; }
        public Nullable<int> ProductBrandId { get; set; }
        public string SyncId { get; set; }
        public int TypeId { get; set; }
        public string Name { get; set; }
        public Nullable<int> ShowNumber { get; set; }
        public bool IsRequired { get; set; }
        public string SyncName { get; set; }
        public Nullable<System.DateTime> SyncDatetime { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Code Code { get; set; }
        public virtual ProductBrand ProductBrand { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductSubCategory ProductSubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCustomFieldLanguage> ProductCustomFieldLanguage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCustomItem> ProductCustomItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCustomValue> ProductCustomValue { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
