//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategoryCompany
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Label { get; set; }
        public string Description { get; set; }
        public Nullable<int> ShowNumber { get; set; }
        public bool Active { get; set; }
        public string Title { get; set; }
        public string SyncName { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
    
        public virtual ProductSubCategory ProductSubCategory { get; set; }
    }
}
