//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopResellerGallery
    {
        public int ID { get; set; }
        public int ResellerId { get; set; }
        public Nullable<int> FileId { get; set; }
        public Nullable<int> PictureId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual Picture Picture { get; set; }
        public virtual ShopReseller ShopReseller { get; set; }
        public virtual WebsiteDocument WebsiteDocument { get; set; }
    }
}
