//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopResellerStory
    {
        public int ID { get; set; }
        public int ShopResellerId { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> PictureId { get; set; }
        public Nullable<int> CollectionId { get; set; }
        public Nullable<int> GalleryId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDatetime { get; set; }
    
        public virtual Picture Picture { get; set; }
        public virtual ShopReseller ShopReseller { get; set; }
    }
}
