//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopResellerCollectionProduct
    {
        public int ID { get; set; }
        public Nullable<int> CollectionId { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<int> ProductBrandId { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public Nullable<int> ProductSubCategoryId { get; set; }
        public Nullable<int> ProductId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductBrand ProductBrand { get; set; }
        public virtual ShopResellerCollection ShopResellerCollection { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
