//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopPaymentType
    {
        public int ID { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
    
        public virtual PaymentType PaymentType { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
