//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaticPage
    {
        public int ID { get; set; }
        public int CategoryId { get; set; }
        public string Title { get; set; }
        public string Html { get; set; }
        public Nullable<int> PictureId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Picture Picture { get; set; }
    }
}
