//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyAnswer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SurveyAnswer()
        {
            this.SurveyAnswerDetail = new HashSet<SurveyAnswerDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<int> SurveyId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Survey Survey { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyAnswerDetail> SurveyAnswerDetail { get; set; }
    }
}
