//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelegramKeyBoard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TelegramKeyBoard()
        {
            this.TelegramCommand = new HashSet<TelegramCommand>();
            this.TelegramKeyBoardItem = new HashSet<TelegramKeyBoardItem>();
        }
    
        public int ID { get; set; }
        public int BotId { get; set; }
        public int TypeId { get; set; }
        public string Name { get; set; }
    
        public virtual Code Code { get; set; }
        public virtual TelegramBot TelegramBot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TelegramCommand> TelegramCommand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TelegramKeyBoardItem> TelegramKeyBoardItem { get; set; }
    }
}
