//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelegramAccount
    {
        public int ID { get; set; }
        public int BotId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string ChatId { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string LanguageCode { get; set; }
        public string Mobile { get; set; }
        public Nullable<bool> IsBot { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public System.DateTime UpdateDatetime { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual SiteUser SiteUser { get; set; }
        public virtual TelegramBot TelegramBot { get; set; }
    }
}
