//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroupDashboard
    {
        public int ID { get; set; }
        public int UserGroupId { get; set; }
        public int DashboardId { get; set; }
    
        public virtual Dashboard Dashboard { get; set; }
        public virtual UserGroup UserGroup { get; set; }
    }
}
