//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VersionUpdate
    {
        public int ID { get; set; }
        public int UserId { get; set; }
        public string Body { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public System.DateTime StartDatetime { get; set; }
        public System.DateTime EndDatetime { get; set; }
        public bool Active { get; set; }
    
        public virtual SiteUser SiteUser { get; set; }
    }
}
