//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteContactForm
    {
        public int ID { get; set; }
        public Nullable<int> WebsiteId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Website { get; set; }
        public string Body { get; set; }
        public string AnswerString { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public System.DateTime Datetime { get; set; }
        public Nullable<System.DateTime> AnswerDatetime { get; set; }
        public string Subject { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Website Website1 { get; set; }
    }
}
