//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Services.Sms.Rahavard {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="STC_SMSSend", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class STC_SMSSend : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string smsIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SourceNumber {
            get {
                return this.SourceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceNumberField, value) != true)) {
                    this.SourceNumberField = value;
                    this.RaisePropertyChanged("SourceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string RecipientNumber {
            get {
                return this.RecipientNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientNumberField, value) != true)) {
                    this.RecipientNumberField = value;
                    this.RaisePropertyChanged("RecipientNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string smsId {
            get {
                return this.smsIdField;
            }
            set {
                if ((object.ReferenceEquals(this.smsIdField, value) != true)) {
                    this.smsIdField = value;
                    this.RaisePropertyChanged("smsId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="STC_SMSStatus", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class STC_SMSStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SendDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RecipientNumber {
            get {
                return this.RecipientNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientNumberField, value) != true)) {
                    this.RecipientNumberField = value;
                    this.RaisePropertyChanged("RecipientNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DeliveryStatus {
            get {
                return this.DeliveryStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryStatusField, value) != true)) {
                    this.DeliveryStatusField = value;
                    this.RaisePropertyChanged("DeliveryStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SendDate {
            get {
                return this.SendDateField;
            }
            set {
                if ((object.ReferenceEquals(this.SendDateField, value) != true)) {
                    this.SendDateField = value;
                    this.RaisePropertyChanged("SendDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.Sms.Rahavard.SendWebServiceSoap")]
    public interface SendWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS_Single", ReplyAction="*")]
        DataLayer.Services.Sms.Rahavard.SendSMS_SingleResponse SendSMS_Single(DataLayer.Services.Sms.Rahavard.SendSMS_SingleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS_Single", ReplyAction="*")]
        System.Threading.Tasks.Task<DataLayer.Services.Sms.Rahavard.SendSMS_SingleResponse> SendSMS_SingleAsync(DataLayer.Services.Sms.Rahavard.SendSMS_SingleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS_Batch_Normal", ReplyAction="*")]
        DataLayer.Services.Sms.Rahavard.SendSMS_Batch_NormalResponse SendSMS_Batch_Normal(DataLayer.Services.Sms.Rahavard.SendSMS_Batch_NormalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS_Batch_Normal", ReplyAction="*")]
        System.Threading.Tasks.Task<DataLayer.Services.Sms.Rahavard.SendSMS_Batch_NormalResponse> SendSMS_Batch_NormalAsync(DataLayer.Services.Sms.Rahavard.SendSMS_Batch_NormalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS_LikeToLike", ReplyAction="*")]
        DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLikeResponse SendSMS_LikeToLike(DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLikeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS_LikeToLike", ReplyAction="*")]
        System.Threading.Tasks.Task<DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLikeResponse> SendSMS_LikeToLikeAsync(DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLikeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS_LikeToLike_Full", ReplyAction="*")]
        DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLike_FullResponse SendSMS_LikeToLike_Full(DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLike_FullRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS_LikeToLike_Full", ReplyAction="*")]
        System.Threading.Tasks.Task<DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLike_FullResponse> SendSMS_LikeToLike_FullAsync(DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLike_FullRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StatusSMS", ReplyAction="*")]
        DataLayer.Services.Sms.Rahavard.StatusSMSResponse StatusSMS(DataLayer.Services.Sms.Rahavard.StatusSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StatusSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<DataLayer.Services.Sms.Rahavard.StatusSMSResponse> StatusSMSAsync(DataLayer.Services.Sms.Rahavard.StatusSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SingleStatusSMS", ReplyAction="*")]
        DataLayer.Services.Sms.Rahavard.SingleStatusSMSResponse SingleStatusSMS(DataLayer.Services.Sms.Rahavard.SingleStatusSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SingleStatusSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<DataLayer.Services.Sms.Rahavard.SingleStatusSMSResponse> SingleStatusSMSAsync(DataLayer.Services.Sms.Rahavard.SingleStatusSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRemainCredit", ReplyAction="*")]
        DataLayer.Services.Sms.Rahavard.GetRemainCreditResponse GetRemainCredit(DataLayer.Services.Sms.Rahavard.GetRemainCreditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRemainCredit", ReplyAction="*")]
        System.Threading.Tasks.Task<DataLayer.Services.Sms.Rahavard.GetRemainCreditResponse> GetRemainCreditAsync(DataLayer.Services.Sms.Rahavard.GetRemainCreditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsBlackList", ReplyAction="*")]
        DataLayer.Services.Sms.Rahavard.IsBlackListResponse IsBlackList(DataLayer.Services.Sms.Rahavard.IsBlackListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsBlackList", ReplyAction="*")]
        System.Threading.Tasks.Task<DataLayer.Services.Sms.Rahavard.IsBlackListResponse> IsBlackListAsync(DataLayer.Services.Sms.Rahavard.IsBlackListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMS_SingleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS_Single", Namespace="http://tempuri.org/", Order=0)]
        public DataLayer.Services.Sms.Rahavard.SendSMS_SingleRequestBody Body;
        
        public SendSMS_SingleRequest() {
        }
        
        public SendSMS_SingleRequest(DataLayer.Services.Sms.Rahavard.SendSMS_SingleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMS_SingleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strServiceID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strServiceToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strMessageText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strRecipientNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strSenderNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string strNumberUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string strNumberPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string strNumberCompany;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string strIP;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string strResultMessage;
        
        public SendSMS_SingleRequestBody() {
        }
        
        public SendSMS_SingleRequestBody(string strServiceID, string strServiceToken, string strMessageText, string strRecipientNumber, string strSenderNumber, string strNumberUsername, string strNumberPassword, string strNumberCompany, string strIP, string strResultMessage) {
            this.strServiceID = strServiceID;
            this.strServiceToken = strServiceToken;
            this.strMessageText = strMessageText;
            this.strRecipientNumber = strRecipientNumber;
            this.strSenderNumber = strSenderNumber;
            this.strNumberUsername = strNumberUsername;
            this.strNumberPassword = strNumberPassword;
            this.strNumberCompany = strNumberCompany;
            this.strIP = strIP;
            this.strResultMessage = strResultMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMS_SingleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS_SingleResponse", Namespace="http://tempuri.org/", Order=0)]
        public DataLayer.Services.Sms.Rahavard.SendSMS_SingleResponseBody Body;
        
        public SendSMS_SingleResponse() {
        }
        
        public SendSMS_SingleResponse(DataLayer.Services.Sms.Rahavard.SendSMS_SingleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMS_SingleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendSMS_SingleResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strResultMessage;
        
        public SendSMS_SingleResponseBody() {
        }
        
        public SendSMS_SingleResponseBody(bool SendSMS_SingleResult, string strResultMessage) {
            this.SendSMS_SingleResult = SendSMS_SingleResult;
            this.strResultMessage = strResultMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMS_Batch_NormalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS_Batch_Normal", Namespace="http://tempuri.org/", Order=0)]
        public DataLayer.Services.Sms.Rahavard.SendSMS_Batch_NormalRequestBody Body;
        
        public SendSMS_Batch_NormalRequest() {
        }
        
        public SendSMS_Batch_NormalRequest(DataLayer.Services.Sms.Rahavard.SendSMS_Batch_NormalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMS_Batch_NormalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strServiceID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strServiceToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strMessageText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public DataLayer.Services.Sms.Rahavard.ArrayOfString arrRecipientNumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strSenderNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string strNumberUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string strNumberPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string strNumberCompany;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public DataLayer.Services.Sms.Rahavard.ArrayOfString arrBatch;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string strResultMessage;
        
        public SendSMS_Batch_NormalRequestBody() {
        }
        
        public SendSMS_Batch_NormalRequestBody(string strServiceID, string strServiceToken, string strMessageText, DataLayer.Services.Sms.Rahavard.ArrayOfString arrRecipientNumbers, string strSenderNumber, string strNumberUsername, string strNumberPassword, string strNumberCompany, DataLayer.Services.Sms.Rahavard.ArrayOfString arrBatch, string strResultMessage) {
            this.strServiceID = strServiceID;
            this.strServiceToken = strServiceToken;
            this.strMessageText = strMessageText;
            this.arrRecipientNumbers = arrRecipientNumbers;
            this.strSenderNumber = strSenderNumber;
            this.strNumberUsername = strNumberUsername;
            this.strNumberPassword = strNumberPassword;
            this.strNumberCompany = strNumberCompany;
            this.arrBatch = arrBatch;
            this.strResultMessage = strResultMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMS_Batch_NormalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS_Batch_NormalResponse", Namespace="http://tempuri.org/", Order=0)]
        public DataLayer.Services.Sms.Rahavard.SendSMS_Batch_NormalResponseBody Body;
        
        public SendSMS_Batch_NormalResponse() {
        }
        
        public SendSMS_Batch_NormalResponse(DataLayer.Services.Sms.Rahavard.SendSMS_Batch_NormalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMS_Batch_NormalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendSMS_Batch_NormalResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public DataLayer.Services.Sms.Rahavard.ArrayOfString arrBatch;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strResultMessage;
        
        public SendSMS_Batch_NormalResponseBody() {
        }
        
        public SendSMS_Batch_NormalResponseBody(bool SendSMS_Batch_NormalResult, DataLayer.Services.Sms.Rahavard.ArrayOfString arrBatch, string strResultMessage) {
            this.SendSMS_Batch_NormalResult = SendSMS_Batch_NormalResult;
            this.arrBatch = arrBatch;
            this.strResultMessage = strResultMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMS_LikeToLikeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS_LikeToLike", Namespace="http://tempuri.org/", Order=0)]
        public DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLikeRequestBody Body;
        
        public SendSMS_LikeToLikeRequest() {
        }
        
        public SendSMS_LikeToLikeRequest(DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLikeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMS_LikeToLikeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strServiceID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strServiceToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public DataLayer.Services.Sms.Rahavard.ArrayOfString arrMessageText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public DataLayer.Services.Sms.Rahavard.ArrayOfString arrRecipientNumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strSenderNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string strNumberUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string strNumberPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string strNumberCompany;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string strIP;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string strResultMessage;
        
        public SendSMS_LikeToLikeRequestBody() {
        }
        
        public SendSMS_LikeToLikeRequestBody(string strServiceID, string strServiceToken, DataLayer.Services.Sms.Rahavard.ArrayOfString arrMessageText, DataLayer.Services.Sms.Rahavard.ArrayOfString arrRecipientNumbers, string strSenderNumber, string strNumberUsername, string strNumberPassword, string strNumberCompany, string strIP, string strResultMessage) {
            this.strServiceID = strServiceID;
            this.strServiceToken = strServiceToken;
            this.arrMessageText = arrMessageText;
            this.arrRecipientNumbers = arrRecipientNumbers;
            this.strSenderNumber = strSenderNumber;
            this.strNumberUsername = strNumberUsername;
            this.strNumberPassword = strNumberPassword;
            this.strNumberCompany = strNumberCompany;
            this.strIP = strIP;
            this.strResultMessage = strResultMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMS_LikeToLikeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS_LikeToLikeResponse", Namespace="http://tempuri.org/", Order=0)]
        public DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLikeResponseBody Body;
        
        public SendSMS_LikeToLikeResponse() {
        }
        
        public SendSMS_LikeToLikeResponse(DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLikeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMS_LikeToLikeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendSMS_LikeToLikeResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strResultMessage;
        
        public SendSMS_LikeToLikeResponseBody() {
        }
        
        public SendSMS_LikeToLikeResponseBody(bool SendSMS_LikeToLikeResult, string strResultMessage) {
            this.SendSMS_LikeToLikeResult = SendSMS_LikeToLikeResult;
            this.strResultMessage = strResultMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMS_LikeToLike_FullRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS_LikeToLike_Full", Namespace="http://tempuri.org/", Order=0)]
        public DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLike_FullRequestBody Body;
        
        public SendSMS_LikeToLike_FullRequest() {
        }
        
        public SendSMS_LikeToLike_FullRequest(DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLike_FullRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMS_LikeToLike_FullRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strServiceID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strServiceToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public DataLayer.Services.Sms.Rahavard.ArrayOfString arrMessageText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public DataLayer.Services.Sms.Rahavard.ArrayOfString arrRecipientNumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strSenderNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string strNumberUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string strNumberPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string strNumberCompany;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string strIP;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string strResultMessage;
        
        public SendSMS_LikeToLike_FullRequestBody() {
        }
        
        public SendSMS_LikeToLike_FullRequestBody(string strServiceID, string strServiceToken, DataLayer.Services.Sms.Rahavard.ArrayOfString arrMessageText, DataLayer.Services.Sms.Rahavard.ArrayOfString arrRecipientNumbers, string strSenderNumber, string strNumberUsername, string strNumberPassword, string strNumberCompany, string strIP, string strResultMessage) {
            this.strServiceID = strServiceID;
            this.strServiceToken = strServiceToken;
            this.arrMessageText = arrMessageText;
            this.arrRecipientNumbers = arrRecipientNumbers;
            this.strSenderNumber = strSenderNumber;
            this.strNumberUsername = strNumberUsername;
            this.strNumberPassword = strNumberPassword;
            this.strNumberCompany = strNumberCompany;
            this.strIP = strIP;
            this.strResultMessage = strResultMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMS_LikeToLike_FullResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS_LikeToLike_FullResponse", Namespace="http://tempuri.org/", Order=0)]
        public DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLike_FullResponseBody Body;
        
        public SendSMS_LikeToLike_FullResponse() {
        }
        
        public SendSMS_LikeToLike_FullResponse(DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLike_FullResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMS_LikeToLike_FullResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DataLayer.Services.Sms.Rahavard.STC_SMSSend[] SendSMS_LikeToLike_FullResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strResultMessage;
        
        public SendSMS_LikeToLike_FullResponseBody() {
        }
        
        public SendSMS_LikeToLike_FullResponseBody(DataLayer.Services.Sms.Rahavard.STC_SMSSend[] SendSMS_LikeToLike_FullResult, string strResultMessage) {
            this.SendSMS_LikeToLike_FullResult = SendSMS_LikeToLike_FullResult;
            this.strResultMessage = strResultMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatusSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StatusSMS", Namespace="http://tempuri.org/", Order=0)]
        public DataLayer.Services.Sms.Rahavard.StatusSMSRequestBody Body;
        
        public StatusSMSRequest() {
        }
        
        public StatusSMSRequest(DataLayer.Services.Sms.Rahavard.StatusSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StatusSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strServiceID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strServiceToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strNumberUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strNumberPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strNumberCompany;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string strIP;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string strBatchID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string strResultMessage;
        
        public StatusSMSRequestBody() {
        }
        
        public StatusSMSRequestBody(string strServiceID, string strServiceToken, string strNumberUsername, string strNumberPassword, string strNumberCompany, string strIP, string strBatchID, string strResultMessage) {
            this.strServiceID = strServiceID;
            this.strServiceToken = strServiceToken;
            this.strNumberUsername = strNumberUsername;
            this.strNumberPassword = strNumberPassword;
            this.strNumberCompany = strNumberCompany;
            this.strIP = strIP;
            this.strBatchID = strBatchID;
            this.strResultMessage = strResultMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatusSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StatusSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public DataLayer.Services.Sms.Rahavard.StatusSMSResponseBody Body;
        
        public StatusSMSResponse() {
        }
        
        public StatusSMSResponse(DataLayer.Services.Sms.Rahavard.StatusSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StatusSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DataLayer.Services.Sms.Rahavard.STC_SMSStatus[] StatusSMSResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strResultMessage;
        
        public StatusSMSResponseBody() {
        }
        
        public StatusSMSResponseBody(DataLayer.Services.Sms.Rahavard.STC_SMSStatus[] StatusSMSResult, string strResultMessage) {
            this.StatusSMSResult = StatusSMSResult;
            this.strResultMessage = strResultMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SingleStatusSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SingleStatusSMS", Namespace="http://tempuri.org/", Order=0)]
        public DataLayer.Services.Sms.Rahavard.SingleStatusSMSRequestBody Body;
        
        public SingleStatusSMSRequest() {
        }
        
        public SingleStatusSMSRequest(DataLayer.Services.Sms.Rahavard.SingleStatusSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SingleStatusSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strServiceID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strServiceToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strNumberUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strNumberPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strNumberCompany;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string strIP;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string strSMSID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string strResultMessage;
        
        public SingleStatusSMSRequestBody() {
        }
        
        public SingleStatusSMSRequestBody(string strServiceID, string strServiceToken, string strNumberUsername, string strNumberPassword, string strNumberCompany, string strIP, string strSMSID, string strResultMessage) {
            this.strServiceID = strServiceID;
            this.strServiceToken = strServiceToken;
            this.strNumberUsername = strNumberUsername;
            this.strNumberPassword = strNumberPassword;
            this.strNumberCompany = strNumberCompany;
            this.strIP = strIP;
            this.strSMSID = strSMSID;
            this.strResultMessage = strResultMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SingleStatusSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SingleStatusSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public DataLayer.Services.Sms.Rahavard.SingleStatusSMSResponseBody Body;
        
        public SingleStatusSMSResponse() {
        }
        
        public SingleStatusSMSResponse(DataLayer.Services.Sms.Rahavard.SingleStatusSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SingleStatusSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DataLayer.Services.Sms.Rahavard.ArrayOfAnyType SingleStatusSMSResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strResultMessage;
        
        public SingleStatusSMSResponseBody() {
        }
        
        public SingleStatusSMSResponseBody(DataLayer.Services.Sms.Rahavard.ArrayOfAnyType SingleStatusSMSResult, string strResultMessage) {
            this.SingleStatusSMSResult = SingleStatusSMSResult;
            this.strResultMessage = strResultMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRemainCreditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRemainCredit", Namespace="http://tempuri.org/", Order=0)]
        public DataLayer.Services.Sms.Rahavard.GetRemainCreditRequestBody Body;
        
        public GetRemainCreditRequest() {
        }
        
        public GetRemainCreditRequest(DataLayer.Services.Sms.Rahavard.GetRemainCreditRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRemainCreditRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strServiceID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strServiceToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strNumberUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strNumberPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strNumberCompany;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string strIP;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string strResultMessage;
        
        public GetRemainCreditRequestBody() {
        }
        
        public GetRemainCreditRequestBody(string strServiceID, string strServiceToken, string strNumberUsername, string strNumberPassword, string strNumberCompany, string strIP, string strResultMessage) {
            this.strServiceID = strServiceID;
            this.strServiceToken = strServiceToken;
            this.strNumberUsername = strNumberUsername;
            this.strNumberPassword = strNumberPassword;
            this.strNumberCompany = strNumberCompany;
            this.strIP = strIP;
            this.strResultMessage = strResultMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRemainCreditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRemainCreditResponse", Namespace="http://tempuri.org/", Order=0)]
        public DataLayer.Services.Sms.Rahavard.GetRemainCreditResponseBody Body;
        
        public GetRemainCreditResponse() {
        }
        
        public GetRemainCreditResponse(DataLayer.Services.Sms.Rahavard.GetRemainCreditResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRemainCreditResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetRemainCreditResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strResultMessage;
        
        public GetRemainCreditResponseBody() {
        }
        
        public GetRemainCreditResponseBody(string GetRemainCreditResult, string strResultMessage) {
            this.GetRemainCreditResult = GetRemainCreditResult;
            this.strResultMessage = strResultMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsBlackListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsBlackList", Namespace="http://tempuri.org/", Order=0)]
        public DataLayer.Services.Sms.Rahavard.IsBlackListRequestBody Body;
        
        public IsBlackListRequest() {
        }
        
        public IsBlackListRequest(DataLayer.Services.Sms.Rahavard.IsBlackListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsBlackListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strServiceID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strServiceToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strMobileNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strResultMessage;
        
        public IsBlackListRequestBody() {
        }
        
        public IsBlackListRequestBody(string strServiceID, string strServiceToken, string strMobileNumber, string strResultMessage) {
            this.strServiceID = strServiceID;
            this.strServiceToken = strServiceToken;
            this.strMobileNumber = strMobileNumber;
            this.strResultMessage = strResultMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsBlackListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsBlackListResponse", Namespace="http://tempuri.org/", Order=0)]
        public DataLayer.Services.Sms.Rahavard.IsBlackListResponseBody Body;
        
        public IsBlackListResponse() {
        }
        
        public IsBlackListResponse(DataLayer.Services.Sms.Rahavard.IsBlackListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsBlackListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsBlackListResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strResultMessage;
        
        public IsBlackListResponseBody() {
        }
        
        public IsBlackListResponseBody(bool IsBlackListResult, string strResultMessage) {
            this.IsBlackListResult = IsBlackListResult;
            this.strResultMessage = strResultMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendWebServiceSoapChannel : DataLayer.Services.Sms.Rahavard.SendWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendWebServiceSoapClient : System.ServiceModel.ClientBase<DataLayer.Services.Sms.Rahavard.SendWebServiceSoap>, DataLayer.Services.Sms.Rahavard.SendWebServiceSoap {
        
        public SendWebServiceSoapClient() {
        }
        
        public SendWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataLayer.Services.Sms.Rahavard.SendSMS_SingleResponse DataLayer.Services.Sms.Rahavard.SendWebServiceSoap.SendSMS_Single(DataLayer.Services.Sms.Rahavard.SendSMS_SingleRequest request) {
            return base.Channel.SendSMS_Single(request);
        }
        
        public bool SendSMS_Single(string strServiceID, string strServiceToken, string strMessageText, string strRecipientNumber, string strSenderNumber, string strNumberUsername, string strNumberPassword, string strNumberCompany, string strIP, ref string strResultMessage) {
            DataLayer.Services.Sms.Rahavard.SendSMS_SingleRequest inValue = new DataLayer.Services.Sms.Rahavard.SendSMS_SingleRequest();
            inValue.Body = new DataLayer.Services.Sms.Rahavard.SendSMS_SingleRequestBody();
            inValue.Body.strServiceID = strServiceID;
            inValue.Body.strServiceToken = strServiceToken;
            inValue.Body.strMessageText = strMessageText;
            inValue.Body.strRecipientNumber = strRecipientNumber;
            inValue.Body.strSenderNumber = strSenderNumber;
            inValue.Body.strNumberUsername = strNumberUsername;
            inValue.Body.strNumberPassword = strNumberPassword;
            inValue.Body.strNumberCompany = strNumberCompany;
            inValue.Body.strIP = strIP;
            inValue.Body.strResultMessage = strResultMessage;
            DataLayer.Services.Sms.Rahavard.SendSMS_SingleResponse retVal = ((DataLayer.Services.Sms.Rahavard.SendWebServiceSoap)(this)).SendSMS_Single(inValue);
            strResultMessage = retVal.Body.strResultMessage;
            return retVal.Body.SendSMS_SingleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataLayer.Services.Sms.Rahavard.SendSMS_SingleResponse> DataLayer.Services.Sms.Rahavard.SendWebServiceSoap.SendSMS_SingleAsync(DataLayer.Services.Sms.Rahavard.SendSMS_SingleRequest request) {
            return base.Channel.SendSMS_SingleAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataLayer.Services.Sms.Rahavard.SendSMS_SingleResponse> SendSMS_SingleAsync(string strServiceID, string strServiceToken, string strMessageText, string strRecipientNumber, string strSenderNumber, string strNumberUsername, string strNumberPassword, string strNumberCompany, string strIP, string strResultMessage) {
            DataLayer.Services.Sms.Rahavard.SendSMS_SingleRequest inValue = new DataLayer.Services.Sms.Rahavard.SendSMS_SingleRequest();
            inValue.Body = new DataLayer.Services.Sms.Rahavard.SendSMS_SingleRequestBody();
            inValue.Body.strServiceID = strServiceID;
            inValue.Body.strServiceToken = strServiceToken;
            inValue.Body.strMessageText = strMessageText;
            inValue.Body.strRecipientNumber = strRecipientNumber;
            inValue.Body.strSenderNumber = strSenderNumber;
            inValue.Body.strNumberUsername = strNumberUsername;
            inValue.Body.strNumberPassword = strNumberPassword;
            inValue.Body.strNumberCompany = strNumberCompany;
            inValue.Body.strIP = strIP;
            inValue.Body.strResultMessage = strResultMessage;
            return ((DataLayer.Services.Sms.Rahavard.SendWebServiceSoap)(this)).SendSMS_SingleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataLayer.Services.Sms.Rahavard.SendSMS_Batch_NormalResponse DataLayer.Services.Sms.Rahavard.SendWebServiceSoap.SendSMS_Batch_Normal(DataLayer.Services.Sms.Rahavard.SendSMS_Batch_NormalRequest request) {
            return base.Channel.SendSMS_Batch_Normal(request);
        }
        
        public bool SendSMS_Batch_Normal(string strServiceID, string strServiceToken, string strMessageText, DataLayer.Services.Sms.Rahavard.ArrayOfString arrRecipientNumbers, string strSenderNumber, string strNumberUsername, string strNumberPassword, string strNumberCompany, ref DataLayer.Services.Sms.Rahavard.ArrayOfString arrBatch, ref string strResultMessage) {
            DataLayer.Services.Sms.Rahavard.SendSMS_Batch_NormalRequest inValue = new DataLayer.Services.Sms.Rahavard.SendSMS_Batch_NormalRequest();
            inValue.Body = new DataLayer.Services.Sms.Rahavard.SendSMS_Batch_NormalRequestBody();
            inValue.Body.strServiceID = strServiceID;
            inValue.Body.strServiceToken = strServiceToken;
            inValue.Body.strMessageText = strMessageText;
            inValue.Body.arrRecipientNumbers = arrRecipientNumbers;
            inValue.Body.strSenderNumber = strSenderNumber;
            inValue.Body.strNumberUsername = strNumberUsername;
            inValue.Body.strNumberPassword = strNumberPassword;
            inValue.Body.strNumberCompany = strNumberCompany;
            inValue.Body.arrBatch = arrBatch;
            inValue.Body.strResultMessage = strResultMessage;
            DataLayer.Services.Sms.Rahavard.SendSMS_Batch_NormalResponse retVal = ((DataLayer.Services.Sms.Rahavard.SendWebServiceSoap)(this)).SendSMS_Batch_Normal(inValue);
            arrBatch = retVal.Body.arrBatch;
            strResultMessage = retVal.Body.strResultMessage;
            return retVal.Body.SendSMS_Batch_NormalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataLayer.Services.Sms.Rahavard.SendSMS_Batch_NormalResponse> DataLayer.Services.Sms.Rahavard.SendWebServiceSoap.SendSMS_Batch_NormalAsync(DataLayer.Services.Sms.Rahavard.SendSMS_Batch_NormalRequest request) {
            return base.Channel.SendSMS_Batch_NormalAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataLayer.Services.Sms.Rahavard.SendSMS_Batch_NormalResponse> SendSMS_Batch_NormalAsync(string strServiceID, string strServiceToken, string strMessageText, DataLayer.Services.Sms.Rahavard.ArrayOfString arrRecipientNumbers, string strSenderNumber, string strNumberUsername, string strNumberPassword, string strNumberCompany, DataLayer.Services.Sms.Rahavard.ArrayOfString arrBatch, string strResultMessage) {
            DataLayer.Services.Sms.Rahavard.SendSMS_Batch_NormalRequest inValue = new DataLayer.Services.Sms.Rahavard.SendSMS_Batch_NormalRequest();
            inValue.Body = new DataLayer.Services.Sms.Rahavard.SendSMS_Batch_NormalRequestBody();
            inValue.Body.strServiceID = strServiceID;
            inValue.Body.strServiceToken = strServiceToken;
            inValue.Body.strMessageText = strMessageText;
            inValue.Body.arrRecipientNumbers = arrRecipientNumbers;
            inValue.Body.strSenderNumber = strSenderNumber;
            inValue.Body.strNumberUsername = strNumberUsername;
            inValue.Body.strNumberPassword = strNumberPassword;
            inValue.Body.strNumberCompany = strNumberCompany;
            inValue.Body.arrBatch = arrBatch;
            inValue.Body.strResultMessage = strResultMessage;
            return ((DataLayer.Services.Sms.Rahavard.SendWebServiceSoap)(this)).SendSMS_Batch_NormalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLikeResponse DataLayer.Services.Sms.Rahavard.SendWebServiceSoap.SendSMS_LikeToLike(DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLikeRequest request) {
            return base.Channel.SendSMS_LikeToLike(request);
        }
        
        public bool SendSMS_LikeToLike(string strServiceID, string strServiceToken, DataLayer.Services.Sms.Rahavard.ArrayOfString arrMessageText, DataLayer.Services.Sms.Rahavard.ArrayOfString arrRecipientNumbers, string strSenderNumber, string strNumberUsername, string strNumberPassword, string strNumberCompany, string strIP, ref string strResultMessage) {
            DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLikeRequest inValue = new DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLikeRequest();
            inValue.Body = new DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLikeRequestBody();
            inValue.Body.strServiceID = strServiceID;
            inValue.Body.strServiceToken = strServiceToken;
            inValue.Body.arrMessageText = arrMessageText;
            inValue.Body.arrRecipientNumbers = arrRecipientNumbers;
            inValue.Body.strSenderNumber = strSenderNumber;
            inValue.Body.strNumberUsername = strNumberUsername;
            inValue.Body.strNumberPassword = strNumberPassword;
            inValue.Body.strNumberCompany = strNumberCompany;
            inValue.Body.strIP = strIP;
            inValue.Body.strResultMessage = strResultMessage;
            DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLikeResponse retVal = ((DataLayer.Services.Sms.Rahavard.SendWebServiceSoap)(this)).SendSMS_LikeToLike(inValue);
            strResultMessage = retVal.Body.strResultMessage;
            return retVal.Body.SendSMS_LikeToLikeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLikeResponse> DataLayer.Services.Sms.Rahavard.SendWebServiceSoap.SendSMS_LikeToLikeAsync(DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLikeRequest request) {
            return base.Channel.SendSMS_LikeToLikeAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLikeResponse> SendSMS_LikeToLikeAsync(string strServiceID, string strServiceToken, DataLayer.Services.Sms.Rahavard.ArrayOfString arrMessageText, DataLayer.Services.Sms.Rahavard.ArrayOfString arrRecipientNumbers, string strSenderNumber, string strNumberUsername, string strNumberPassword, string strNumberCompany, string strIP, string strResultMessage) {
            DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLikeRequest inValue = new DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLikeRequest();
            inValue.Body = new DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLikeRequestBody();
            inValue.Body.strServiceID = strServiceID;
            inValue.Body.strServiceToken = strServiceToken;
            inValue.Body.arrMessageText = arrMessageText;
            inValue.Body.arrRecipientNumbers = arrRecipientNumbers;
            inValue.Body.strSenderNumber = strSenderNumber;
            inValue.Body.strNumberUsername = strNumberUsername;
            inValue.Body.strNumberPassword = strNumberPassword;
            inValue.Body.strNumberCompany = strNumberCompany;
            inValue.Body.strIP = strIP;
            inValue.Body.strResultMessage = strResultMessage;
            return ((DataLayer.Services.Sms.Rahavard.SendWebServiceSoap)(this)).SendSMS_LikeToLikeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLike_FullResponse DataLayer.Services.Sms.Rahavard.SendWebServiceSoap.SendSMS_LikeToLike_Full(DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLike_FullRequest request) {
            return base.Channel.SendSMS_LikeToLike_Full(request);
        }
        
        public DataLayer.Services.Sms.Rahavard.STC_SMSSend[] SendSMS_LikeToLike_Full(string strServiceID, string strServiceToken, DataLayer.Services.Sms.Rahavard.ArrayOfString arrMessageText, DataLayer.Services.Sms.Rahavard.ArrayOfString arrRecipientNumbers, string strSenderNumber, string strNumberUsername, string strNumberPassword, string strNumberCompany, string strIP, ref string strResultMessage) {
            DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLike_FullRequest inValue = new DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLike_FullRequest();
            inValue.Body = new DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLike_FullRequestBody();
            inValue.Body.strServiceID = strServiceID;
            inValue.Body.strServiceToken = strServiceToken;
            inValue.Body.arrMessageText = arrMessageText;
            inValue.Body.arrRecipientNumbers = arrRecipientNumbers;
            inValue.Body.strSenderNumber = strSenderNumber;
            inValue.Body.strNumberUsername = strNumberUsername;
            inValue.Body.strNumberPassword = strNumberPassword;
            inValue.Body.strNumberCompany = strNumberCompany;
            inValue.Body.strIP = strIP;
            inValue.Body.strResultMessage = strResultMessage;
            DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLike_FullResponse retVal = ((DataLayer.Services.Sms.Rahavard.SendWebServiceSoap)(this)).SendSMS_LikeToLike_Full(inValue);
            strResultMessage = retVal.Body.strResultMessage;
            return retVal.Body.SendSMS_LikeToLike_FullResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLike_FullResponse> DataLayer.Services.Sms.Rahavard.SendWebServiceSoap.SendSMS_LikeToLike_FullAsync(DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLike_FullRequest request) {
            return base.Channel.SendSMS_LikeToLike_FullAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLike_FullResponse> SendSMS_LikeToLike_FullAsync(string strServiceID, string strServiceToken, DataLayer.Services.Sms.Rahavard.ArrayOfString arrMessageText, DataLayer.Services.Sms.Rahavard.ArrayOfString arrRecipientNumbers, string strSenderNumber, string strNumberUsername, string strNumberPassword, string strNumberCompany, string strIP, string strResultMessage) {
            DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLike_FullRequest inValue = new DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLike_FullRequest();
            inValue.Body = new DataLayer.Services.Sms.Rahavard.SendSMS_LikeToLike_FullRequestBody();
            inValue.Body.strServiceID = strServiceID;
            inValue.Body.strServiceToken = strServiceToken;
            inValue.Body.arrMessageText = arrMessageText;
            inValue.Body.arrRecipientNumbers = arrRecipientNumbers;
            inValue.Body.strSenderNumber = strSenderNumber;
            inValue.Body.strNumberUsername = strNumberUsername;
            inValue.Body.strNumberPassword = strNumberPassword;
            inValue.Body.strNumberCompany = strNumberCompany;
            inValue.Body.strIP = strIP;
            inValue.Body.strResultMessage = strResultMessage;
            return ((DataLayer.Services.Sms.Rahavard.SendWebServiceSoap)(this)).SendSMS_LikeToLike_FullAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataLayer.Services.Sms.Rahavard.StatusSMSResponse DataLayer.Services.Sms.Rahavard.SendWebServiceSoap.StatusSMS(DataLayer.Services.Sms.Rahavard.StatusSMSRequest request) {
            return base.Channel.StatusSMS(request);
        }
        
        public DataLayer.Services.Sms.Rahavard.STC_SMSStatus[] StatusSMS(string strServiceID, string strServiceToken, string strNumberUsername, string strNumberPassword, string strNumberCompany, string strIP, string strBatchID, ref string strResultMessage) {
            DataLayer.Services.Sms.Rahavard.StatusSMSRequest inValue = new DataLayer.Services.Sms.Rahavard.StatusSMSRequest();
            inValue.Body = new DataLayer.Services.Sms.Rahavard.StatusSMSRequestBody();
            inValue.Body.strServiceID = strServiceID;
            inValue.Body.strServiceToken = strServiceToken;
            inValue.Body.strNumberUsername = strNumberUsername;
            inValue.Body.strNumberPassword = strNumberPassword;
            inValue.Body.strNumberCompany = strNumberCompany;
            inValue.Body.strIP = strIP;
            inValue.Body.strBatchID = strBatchID;
            inValue.Body.strResultMessage = strResultMessage;
            DataLayer.Services.Sms.Rahavard.StatusSMSResponse retVal = ((DataLayer.Services.Sms.Rahavard.SendWebServiceSoap)(this)).StatusSMS(inValue);
            strResultMessage = retVal.Body.strResultMessage;
            return retVal.Body.StatusSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataLayer.Services.Sms.Rahavard.StatusSMSResponse> DataLayer.Services.Sms.Rahavard.SendWebServiceSoap.StatusSMSAsync(DataLayer.Services.Sms.Rahavard.StatusSMSRequest request) {
            return base.Channel.StatusSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataLayer.Services.Sms.Rahavard.StatusSMSResponse> StatusSMSAsync(string strServiceID, string strServiceToken, string strNumberUsername, string strNumberPassword, string strNumberCompany, string strIP, string strBatchID, string strResultMessage) {
            DataLayer.Services.Sms.Rahavard.StatusSMSRequest inValue = new DataLayer.Services.Sms.Rahavard.StatusSMSRequest();
            inValue.Body = new DataLayer.Services.Sms.Rahavard.StatusSMSRequestBody();
            inValue.Body.strServiceID = strServiceID;
            inValue.Body.strServiceToken = strServiceToken;
            inValue.Body.strNumberUsername = strNumberUsername;
            inValue.Body.strNumberPassword = strNumberPassword;
            inValue.Body.strNumberCompany = strNumberCompany;
            inValue.Body.strIP = strIP;
            inValue.Body.strBatchID = strBatchID;
            inValue.Body.strResultMessage = strResultMessage;
            return ((DataLayer.Services.Sms.Rahavard.SendWebServiceSoap)(this)).StatusSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataLayer.Services.Sms.Rahavard.SingleStatusSMSResponse DataLayer.Services.Sms.Rahavard.SendWebServiceSoap.SingleStatusSMS(DataLayer.Services.Sms.Rahavard.SingleStatusSMSRequest request) {
            return base.Channel.SingleStatusSMS(request);
        }
        
        public DataLayer.Services.Sms.Rahavard.ArrayOfAnyType SingleStatusSMS(string strServiceID, string strServiceToken, string strNumberUsername, string strNumberPassword, string strNumberCompany, string strIP, string strSMSID, ref string strResultMessage) {
            DataLayer.Services.Sms.Rahavard.SingleStatusSMSRequest inValue = new DataLayer.Services.Sms.Rahavard.SingleStatusSMSRequest();
            inValue.Body = new DataLayer.Services.Sms.Rahavard.SingleStatusSMSRequestBody();
            inValue.Body.strServiceID = strServiceID;
            inValue.Body.strServiceToken = strServiceToken;
            inValue.Body.strNumberUsername = strNumberUsername;
            inValue.Body.strNumberPassword = strNumberPassword;
            inValue.Body.strNumberCompany = strNumberCompany;
            inValue.Body.strIP = strIP;
            inValue.Body.strSMSID = strSMSID;
            inValue.Body.strResultMessage = strResultMessage;
            DataLayer.Services.Sms.Rahavard.SingleStatusSMSResponse retVal = ((DataLayer.Services.Sms.Rahavard.SendWebServiceSoap)(this)).SingleStatusSMS(inValue);
            strResultMessage = retVal.Body.strResultMessage;
            return retVal.Body.SingleStatusSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataLayer.Services.Sms.Rahavard.SingleStatusSMSResponse> DataLayer.Services.Sms.Rahavard.SendWebServiceSoap.SingleStatusSMSAsync(DataLayer.Services.Sms.Rahavard.SingleStatusSMSRequest request) {
            return base.Channel.SingleStatusSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataLayer.Services.Sms.Rahavard.SingleStatusSMSResponse> SingleStatusSMSAsync(string strServiceID, string strServiceToken, string strNumberUsername, string strNumberPassword, string strNumberCompany, string strIP, string strSMSID, string strResultMessage) {
            DataLayer.Services.Sms.Rahavard.SingleStatusSMSRequest inValue = new DataLayer.Services.Sms.Rahavard.SingleStatusSMSRequest();
            inValue.Body = new DataLayer.Services.Sms.Rahavard.SingleStatusSMSRequestBody();
            inValue.Body.strServiceID = strServiceID;
            inValue.Body.strServiceToken = strServiceToken;
            inValue.Body.strNumberUsername = strNumberUsername;
            inValue.Body.strNumberPassword = strNumberPassword;
            inValue.Body.strNumberCompany = strNumberCompany;
            inValue.Body.strIP = strIP;
            inValue.Body.strSMSID = strSMSID;
            inValue.Body.strResultMessage = strResultMessage;
            return ((DataLayer.Services.Sms.Rahavard.SendWebServiceSoap)(this)).SingleStatusSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataLayer.Services.Sms.Rahavard.GetRemainCreditResponse DataLayer.Services.Sms.Rahavard.SendWebServiceSoap.GetRemainCredit(DataLayer.Services.Sms.Rahavard.GetRemainCreditRequest request) {
            return base.Channel.GetRemainCredit(request);
        }
        
        public string GetRemainCredit(string strServiceID, string strServiceToken, string strNumberUsername, string strNumberPassword, string strNumberCompany, string strIP, ref string strResultMessage) {
            DataLayer.Services.Sms.Rahavard.GetRemainCreditRequest inValue = new DataLayer.Services.Sms.Rahavard.GetRemainCreditRequest();
            inValue.Body = new DataLayer.Services.Sms.Rahavard.GetRemainCreditRequestBody();
            inValue.Body.strServiceID = strServiceID;
            inValue.Body.strServiceToken = strServiceToken;
            inValue.Body.strNumberUsername = strNumberUsername;
            inValue.Body.strNumberPassword = strNumberPassword;
            inValue.Body.strNumberCompany = strNumberCompany;
            inValue.Body.strIP = strIP;
            inValue.Body.strResultMessage = strResultMessage;
            DataLayer.Services.Sms.Rahavard.GetRemainCreditResponse retVal = ((DataLayer.Services.Sms.Rahavard.SendWebServiceSoap)(this)).GetRemainCredit(inValue);
            strResultMessage = retVal.Body.strResultMessage;
            return retVal.Body.GetRemainCreditResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataLayer.Services.Sms.Rahavard.GetRemainCreditResponse> DataLayer.Services.Sms.Rahavard.SendWebServiceSoap.GetRemainCreditAsync(DataLayer.Services.Sms.Rahavard.GetRemainCreditRequest request) {
            return base.Channel.GetRemainCreditAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataLayer.Services.Sms.Rahavard.GetRemainCreditResponse> GetRemainCreditAsync(string strServiceID, string strServiceToken, string strNumberUsername, string strNumberPassword, string strNumberCompany, string strIP, string strResultMessage) {
            DataLayer.Services.Sms.Rahavard.GetRemainCreditRequest inValue = new DataLayer.Services.Sms.Rahavard.GetRemainCreditRequest();
            inValue.Body = new DataLayer.Services.Sms.Rahavard.GetRemainCreditRequestBody();
            inValue.Body.strServiceID = strServiceID;
            inValue.Body.strServiceToken = strServiceToken;
            inValue.Body.strNumberUsername = strNumberUsername;
            inValue.Body.strNumberPassword = strNumberPassword;
            inValue.Body.strNumberCompany = strNumberCompany;
            inValue.Body.strIP = strIP;
            inValue.Body.strResultMessage = strResultMessage;
            return ((DataLayer.Services.Sms.Rahavard.SendWebServiceSoap)(this)).GetRemainCreditAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataLayer.Services.Sms.Rahavard.IsBlackListResponse DataLayer.Services.Sms.Rahavard.SendWebServiceSoap.IsBlackList(DataLayer.Services.Sms.Rahavard.IsBlackListRequest request) {
            return base.Channel.IsBlackList(request);
        }
        
        public bool IsBlackList(string strServiceID, string strServiceToken, string strMobileNumber, ref string strResultMessage) {
            DataLayer.Services.Sms.Rahavard.IsBlackListRequest inValue = new DataLayer.Services.Sms.Rahavard.IsBlackListRequest();
            inValue.Body = new DataLayer.Services.Sms.Rahavard.IsBlackListRequestBody();
            inValue.Body.strServiceID = strServiceID;
            inValue.Body.strServiceToken = strServiceToken;
            inValue.Body.strMobileNumber = strMobileNumber;
            inValue.Body.strResultMessage = strResultMessage;
            DataLayer.Services.Sms.Rahavard.IsBlackListResponse retVal = ((DataLayer.Services.Sms.Rahavard.SendWebServiceSoap)(this)).IsBlackList(inValue);
            strResultMessage = retVal.Body.strResultMessage;
            return retVal.Body.IsBlackListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataLayer.Services.Sms.Rahavard.IsBlackListResponse> DataLayer.Services.Sms.Rahavard.SendWebServiceSoap.IsBlackListAsync(DataLayer.Services.Sms.Rahavard.IsBlackListRequest request) {
            return base.Channel.IsBlackListAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataLayer.Services.Sms.Rahavard.IsBlackListResponse> IsBlackListAsync(string strServiceID, string strServiceToken, string strMobileNumber, string strResultMessage) {
            DataLayer.Services.Sms.Rahavard.IsBlackListRequest inValue = new DataLayer.Services.Sms.Rahavard.IsBlackListRequest();
            inValue.Body = new DataLayer.Services.Sms.Rahavard.IsBlackListRequestBody();
            inValue.Body.strServiceID = strServiceID;
            inValue.Body.strServiceToken = strServiceToken;
            inValue.Body.strMobileNumber = strMobileNumber;
            inValue.Body.strResultMessage = strResultMessage;
            return ((DataLayer.Services.Sms.Rahavard.SendWebServiceSoap)(this)).IsBlackListAsync(inValue);
        }
    }
}
