//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountLog
    {
        public int ID { get; set; }
        public int AccountId { get; set; }
        public System.Guid AccountKey { get; set; }
        public Nullable<bool> IsWeb { get; set; }
        public Nullable<bool> IsExpired { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
