//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountPasswordForget
    {
        public int ID { get; set; }
        public int AccountId { get; set; }
        public string EmailKey { get; set; }
        public string MobileKey { get; set; }
        public System.DateTime Datetime { get; set; }
        public bool IsUsed { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
