//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountOrder()
        {
            this.AccountOrder1 = new HashSet<AccountOrder>();
            this.AccountOrderComment = new HashSet<AccountOrderComment>();
            this.AccountOrderProduct = new HashSet<AccountOrderProduct>();
            this.PaymentProductOrder = new HashSet<PaymentProductOrder>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ShopId { get; set; }
        public int AccountId { get; set; }
        public Nullable<int> AddressId { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<int> RebateId { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> SendTypeId { get; set; }
        public double Price { get; set; }
        public string PostalCode { get; set; }
        public System.DateTime Datetime { get; set; }
        public Nullable<double> DiscountPrice { get; set; }
        public Nullable<double> SendPrice { get; set; }
        public string Description { get; set; }
        public Nullable<double> RebatePrice { get; set; }
        public string SyncId { get; set; }
        public Nullable<System.DateTime> SyncDatetime { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> BenefitPercent { get; set; }
        public Nullable<int> ClearingId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<bool> IsGift { get; set; }
        public string GiftDescription { get; set; }
        public Nullable<bool> HasFactor { get; set; }
        public Nullable<int> SendTypeStore { get; set; }
        public double ProductsPrice { get; set; }
        public Nullable<bool> IsCreditShoping { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual AccountAddress AccountAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountOrder> AccountOrder1 { get; set; }
        public virtual AccountOrder AccountOrder2 { get; set; }
        public virtual Clearing Clearing { get; set; }
        public virtual SendType SendType { get; set; }
        public virtual Shop Shop { get; set; }
        public virtual Store Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountOrderComment> AccountOrderComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountOrderProduct> AccountOrderProduct { get; set; }
        public virtual Code Code { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual Rebate Rebate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentProductOrder> PaymentProductOrder { get; set; }
    }
}
