//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountDocument
    {
        public int ID { get; set; }
        public int AccountId { get; set; }
        public int DocId { get; set; }
        public string Name { get; set; }
        public System.DateTime Datetime { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual WebsiteDocument WebsiteDocument { get; set; }
    }
}
