//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountOrderProduct
    {
        public int ID { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> ResellerId { get; set; }
        public int Count { get; set; }
        public double Price { get; set; }
        public System.DateTime Datetime { get; set; }
        public Nullable<double> ProductPrice { get; set; }
        public Nullable<double> ProductDiscount { get; set; }
        public Nullable<int> ColorId { get; set; }
        public Nullable<int> SizeId { get; set; }
        public string SyncId { get; set; }
        public Nullable<System.DateTime> SyncDatetime { get; set; }
        public Nullable<int> OptionItemId { get; set; }
        public int ProductsCount { get; set; }
        public int ProductsTotalCount { get; set; }
    
        public virtual AccountOrder AccountOrder { get; set; }
        public virtual Color Color { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProductOptionItem ProductOptionItem { get; set; }
        public virtual ShopReseller ShopReseller { get; set; }
        public virtual Size Size { get; set; }
    }
}
