//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlexaRank
    {
        public int ID { get; set; }
        public Nullable<int> DomainId { get; set; }
        public Nullable<int> GlobalRank { get; set; }
        public Nullable<int> ReachRank { get; set; }
        public Nullable<int> ReachDelta { get; set; }
        public Nullable<int> CountryRank { get; set; }
        public string CountryName { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
    
        public virtual WebsiteDomain WebsiteDomain { get; set; }
    }
}
