//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int ID { get; set; }
        public Nullable<int> SenderId { get; set; }
        public Nullable<int> ReceiverId { get; set; }
        public string Body { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
    
        public virtual SiteUser SiteUser { get; set; }
        public virtual SiteUser SiteUser1 { get; set; }
    }
}
