//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clearing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clearing()
        {
            this.AccountOrder = new HashSet<AccountOrder>();
        }
    
        public int ID { get; set; }
        public double Price { get; set; }
        public string Detail { get; set; }
        public int StoreId { get; set; }
        public Nullable<int> PictureId { get; set; }
        public int CodeId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string FromAccount { get; set; }
        public string ToAccount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountOrder> AccountOrder { get; set; }
        public virtual Code Code { get; set; }
        public virtual Picture Picture { get; set; }
        public virtual Store Store { get; set; }
    }
}
