//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public int ID { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> UserId { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public Nullable<int> ProductSubCategoryId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ColorId { get; set; }
        public Nullable<double> PriceValue { get; set; }
        public Nullable<int> PercentValue { get; set; }
        public Nullable<System.DateTime> StartDatetime { get; set; }
        public Nullable<System.DateTime> EndDatetime { get; set; }
        public bool Active { get; set; }
        public string Description { get; set; }
        public bool IsTop { get; set; }
        public Nullable<int> ProductBrandId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> StoreProductQuantityId { get; set; }
        public Nullable<int> ValueTypeId { get; set; }
    
        public virtual Code Code { get; set; }
        public virtual Code Code1 { get; set; }
        public virtual Color Color { get; set; }
        public virtual DiscountGroup DiscountGroup { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProductBrand ProductBrand { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductSubCategory ProductSubCategory { get; set; }
        public virtual Shop Shop { get; set; }
        public virtual SiteUser SiteUser { get; set; }
        public virtual Store Store { get; set; }
        public virtual StoreProductQuantity StoreProductQuantity { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
