//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailHost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmailHost()
        {
            this.EmailAddress = new HashSet<EmailAddress>();
        }
    
        public int ID { get; set; }
        public Nullable<int> UserCreatorId { get; set; }
        public string Name { get; set; }
        public string Pop3 { get; set; }
        public string Smtp { get; set; }
        public int Pop3Port { get; set; }
        public int SmtpPort { get; set; }
        public bool Ssl { get; set; }
        public bool AutoSync { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public string Body { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailAddress> EmailAddress { get; set; }
        public virtual SiteUser SiteUser { get; set; }
    }
}
