//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Email()
        {
            this.EmailAttachment = new HashSet<EmailAttachment>();
        }
    
        public int ID { get; set; }
        public int AddressId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Sender { get; set; }
        public string Receive { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<System.DateTime> LastSendDatetime { get; set; }
        public Nullable<bool> IsSend { get; set; }
    
        public virtual EmailAddress EmailAddress { get; set; }
        public virtual EmailType EmailType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailAttachment> EmailAttachment { get; set; }
    }
}
