//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LadderSetting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LadderSetting()
        {
            this.LadderPayment = new HashSet<LadderPayment>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<double> LadderPrice { get; set; }
        public Nullable<int> LadderDays { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> IsProduct { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LadderPayment> LadderPayment { get; set; }
        public virtual LadderSetting LadderSetting1 { get; set; }
        public virtual LadderSetting LadderSetting2 { get; set; }
    }
}
