//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu()
        {
            this.Menu1 = new HashSet<Menu>();
            this.MenuLanguage = new HashSet<MenuLanguage>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> GalleryId { get; set; }
        public Nullable<int> PostId { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public Nullable<int> ShowNumber { get; set; }
        public System.DateTime UpdateDatetime { get; set; }
        public bool Active { get; set; }
        public Nullable<int> PictureId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Code Code { get; set; }
        public virtual Gallery Gallery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu> Menu1 { get; set; }
        public virtual Menu Menu2 { get; set; }
        public virtual Post Post { get; set; }
        public virtual Picture Picture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuLanguage> MenuLanguage { get; set; }
    }
}
