//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Package()
        {
            this.PaymentPackage = new HashSet<PaymentPackage>();
            this.ShopPackage = new HashSet<ShopPackage>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PictureId { get; set; }
        public string Name { get; set; }
        public string Label { get; set; }
        public int Price { get; set; }
        public int DayCount { get; set; }
        public int ProductCount { get; set; }
        public int ProductTypeCount { get; set; }
        public int DiskSpace { get; set; }
        public bool HasTemplate { get; set; }
        public bool HasDomain { get; set; }
        public bool Active { get; set; }
    
        public virtual Picture Picture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentPackage> PaymentPackage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopPackage> ShopPackage { get; set; }
    }
}
