//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentProductOrder
    {
        public int ID { get; set; }
        public int OrderId { get; set; }
        public int PaymentId { get; set; }
    
        public virtual AccountOrder AccountOrder { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
