//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.Comment = new HashSet<Comment>();
            this.Menu = new HashSet<Menu>();
            this.PostLanguage = new HashSet<PostLanguage>();
            this.PostLike = new HashSet<PostLike>();
            this.TagPost = new HashSet<TagPost>();
            this.QuestionPost = new HashSet<QuestionPost>();
        }
    
        public int ID { get; set; }
        public int WebsiteId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> PictureId { get; set; }
        public Nullable<int> FileId { get; set; }
        public string Name { get; set; }
        public string Keywords { get; set; }
        public string Summary { get; set; }
        public string Body { get; set; }
        public Nullable<System.DateTime> ShowDateTime { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public Nullable<int> ShowNumber { get; set; }
        public int VisitCount { get; set; }
        public bool IsSlider { get; set; }
        public bool Active { get; set; }
        public string URL { get; set; }
        public string H1 { get; set; }
        public string Writer { get; set; }
        public string WriterPostion { get; set; }
        public Nullable<int> WriterPictureId { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Aparat { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string MetaDescription { get; set; }
        public string Title { get; set; }
        public string RobotMeta { get; set; }
        public string Canonical { get; set; }
        public string Schema { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu> Menu { get; set; }
        public virtual Picture Picture { get; set; }
        public virtual Picture Picture1 { get; set; }
        public virtual State State { get; set; }
        public virtual Website Website { get; set; }
        public virtual WebsiteDocument WebsiteDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostLanguage> PostLanguage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostLike> PostLike { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TagPost> TagPost { get; set; }
        public virtual City City { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionPost> QuestionPost { get; set; }
    }
}
