//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductType()
        {
            this.Color = new HashSet<Color>();
            this.Discount = new HashSet<Discount>();
            this.Product = new HashSet<Product>();
            this.ProductBrand = new HashSet<ProductBrand>();
            this.ProductCategory = new HashSet<ProductCategory>();
            this.ProductCustomField = new HashSet<ProductCustomField>();
            this.ProductOption = new HashSet<ProductOption>();
            this.ProductTypeBrand = new HashSet<ProductTypeBrand>();
            this.ProductTypeLanguage = new HashSet<ProductTypeLanguage>();
            this.Rebate = new HashSet<Rebate>();
            this.ShopProductType = new HashSet<ShopProductType>();
            this.ShopResellerCollectionProduct = new HashSet<ShopResellerCollectionProduct>();
            this.ShopResellerProduct = new HashSet<ShopResellerProduct>();
            this.Size = new HashSet<Size>();
            this.QuestionProductType = new HashSet<QuestionProductType>();
            this.ProductsType = new HashSet<ProductsType>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> PictureId { get; set; }
        public string SyncId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> SyncDatetime { get; set; }
        public Nullable<int> IconId { get; set; }
        public bool Active { get; set; }
        public string H1 { get; set; }
        public string Url { get; set; }
        public string title { get; set; }
        public string body { get; set; }
        public bool IsService { get; set; }
        public string CustomLabel { get; set; }
        public Nullable<int> AttachFileId1 { get; set; }
        public Nullable<int> AttachFileId2 { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> HaveAddress { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public string MetaDescription { get; set; }
        public string RobotMeta { get; set; }
        public string Canonical { get; set; }
        public string Schema { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Color> Color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discount> Discount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductBrand> ProductBrand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCategory> ProductCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCustomField> ProductCustomField { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOption> ProductOption { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductTypeBrand> ProductTypeBrand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductTypeLanguage> ProductTypeLanguage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rebate> Rebate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopProductType> ShopProductType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopResellerCollectionProduct> ShopResellerCollectionProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopResellerProduct> ShopResellerProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Size> Size { get; set; }
        public virtual Picture Picture { get; set; }
        public virtual WebsiteDocument WebsiteDocument { get; set; }
        public virtual WebsiteDocument WebsiteDocument1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionProductType> QuestionProductType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsType> ProductsType { get; set; }
    }
}
