//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSubCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductSubCategory()
        {
            this.Discount = new HashSet<Discount>();
            this.Product = new HashSet<Product>();
            this.ProductCategoryCompany = new HashSet<ProductCategoryCompany>();
            this.ProductCustomField = new HashSet<ProductCustomField>();
            this.ProductSubCategoryLanguage = new HashSet<ProductSubCategoryLanguage>();
            this.Rebate = new HashSet<Rebate>();
            this.TagSubcategory = new HashSet<TagSubcategory>();
            this.ProductCompany = new HashSet<ProductCompany>();
            this.ProductsSubCategory = new HashSet<ProductsSubCategory>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Priority { get; set; }
        public int CategoryId { get; set; }
        public string SyncId { get; set; }
        public Nullable<int> PictureId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public Nullable<System.DateTime> SyncDatetime { get; set; }
        public Nullable<int> IconId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public string H1 { get; set; }
        public string Body { get; set; }
        public string CustomLabel { get; set; }
        public bool Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string MetaDescription { get; set; }
        public string RobotMeta { get; set; }
        public string Canonical { get; set; }
        public string Schema { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discount> Discount { get; set; }
        public virtual Picture Picture { get; set; }
        public virtual Picture Picture1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCategoryCompany> ProductCategoryCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCustomField> ProductCustomField { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSubCategoryLanguage> ProductSubCategoryLanguage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rebate> Rebate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TagSubcategory> TagSubcategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCompany> ProductCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsSubCategory> ProductsSubCategory { get; set; }
    }
}
