//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionProductTypeLanguage
    {
        public int ID { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public Nullable<int> LanguageId { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual QuestionProductType QuestionProductType { get; set; }
    }
}
