//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rebate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rebate()
        {
            this.AccountOrder = new HashSet<AccountOrder>();
        }
    
        public int ID { get; set; }
        public int UserId { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public Nullable<int> ProductSubCategoryId { get; set; }
        public Nullable<int> ProductBrandId { get; set; }
        public string Name { get; set; }
        public string CodeValue { get; set; }
        public Nullable<int> MinInvoiceValue { get; set; }
        public Nullable<int> MaxInvoiceValue { get; set; }
        public Nullable<int> MaxRebatePrice { get; set; }
        public Nullable<int> PercentValue { get; set; }
        public Nullable<int> PriceValue { get; set; }
        public Nullable<int> UseCount { get; set; }
        public Nullable<System.DateTime> StartDatetime { get; set; }
        public Nullable<System.DateTime> EndDatetime { get; set; }
        public bool IsPriceRebate { get; set; }
        public bool Active { get; set; }
        public string Mobile { get; set; }
        public Nullable<bool> IsFinalPercentPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountOrder> AccountOrder { get; set; }
        public virtual Code Code { get; set; }
        public virtual ProductBrand ProductBrand { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductSubCategory ProductSubCategory { get; set; }
        public virtual Shop Shop { get; set; }
        public virtual SiteUser SiteUser { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
