//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerException
    {
        public int ID { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Url { get; set; }
        public string Message { get; set; }
        public string Code { get; set; }
    
        public virtual SiteUser SiteUser { get; set; }
    }
}
