//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int ID { get; set; }
        public int GroupId { get; set; }
        public Nullable<int> UserId { get; set; }
        public int TypeId { get; set; }
        public string Name { get; set; }
        public string Label { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
    
        public virtual SettingGroup SettingGroup { get; set; }
        public virtual SiteUser SiteUser { get; set; }
    }
}
