//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingCity
    {
        public int ShippingCityId { get; set; }
        public int StoreId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> SendTime { get; set; }
        public Nullable<decimal> SendPrice { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<decimal> MinPriceForFree { get; set; }
        public Nullable<int> SendPricePostP { get; set; }
        public Nullable<int> SendPricePost { get; set; }
        public Nullable<int> SendTimePostP { get; set; }
        public Nullable<int> SendTimePost { get; set; }
        public Nullable<decimal> PriceForCountPost { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
        public virtual Store Store { get; set; }
    }
}
