//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopResellerCollection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShopResellerCollection()
        {
            this.ShopResellerCollectionProduct = new HashSet<ShopResellerCollectionProduct>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PictureId { get; set; }
        public Nullable<int> Picture2Id { get; set; }
        public Nullable<int> Picture3Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> ShowNumber { get; set; }
        public Nullable<int> ResellerId { get; set; }
    
        public virtual Picture Picture { get; set; }
        public virtual Picture Picture1 { get; set; }
        public virtual Picture Picture2 { get; set; }
        public virtual ShopReseller ShopReseller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopResellerCollectionProduct> ShopResellerCollectionProduct { get; set; }
    }
}
