//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shop()
        {
            this.AccountOrder = new HashSet<AccountOrder>();
            this.Discount = new HashSet<Discount>();
            this.GuaranteeCompany = new HashSet<GuaranteeCompany>();
            this.Product = new HashSet<Product>();
            this.Rebate = new HashSet<Rebate>();
            this.ShopAddress = new HashSet<ShopAddress>();
            this.ShopChat = new HashSet<ShopChat>();
            this.ShopContact = new HashSet<ShopContact>();
            this.ShopCustomValue = new HashSet<ShopCustomValue>();
            this.ShopDocument = new HashSet<ShopDocument>();
            this.ShopFollow = new HashSet<ShopFollow>();
            this.ShopPackage = new HashSet<ShopPackage>();
            this.ShopPaymentType = new HashSet<ShopPaymentType>();
            this.ShopPicture = new HashSet<ShopPicture>();
            this.ShopProductType = new HashSet<ShopProductType>();
            this.ShopReportBlock = new HashSet<ShopReportBlock>();
            this.ShopReseller = new HashSet<ShopReseller>();
            this.ShopUser = new HashSet<ShopUser>();
        }
    
        public int ID { get; set; }
        public Nullable<int> UserCreatorId { get; set; }
        public Nullable<int> TemplateId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> CityId { get; set; }
        public int WebsiteId { get; set; }
        public Nullable<int> PictureId { get; set; }
        public Nullable<int> MallId { get; set; }
        public string Name { get; set; }
        public string Label { get; set; }
        public string Description { get; set; }
        public string MainMarket { get; set; }
        public string EmployeeCount { get; set; }
        public bool Approved { get; set; }
        public bool Active { get; set; }
        public Nullable<int> MovieId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountOrder> AccountOrder { get; set; }
        public virtual City City { get; set; }
        public virtual Code Code { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discount> Discount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuaranteeCompany> GuaranteeCompany { get; set; }
        public virtual Mall Mall { get; set; }
        public virtual Picture Picture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rebate> Rebate { get; set; }
        public virtual SiteUser SiteUser { get; set; }
        public virtual Template Template { get; set; }
        public virtual Website Website { get; set; }
        public virtual Website Website1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopAddress> ShopAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopChat> ShopChat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopContact> ShopContact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopCustomValue> ShopCustomValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopDocument> ShopDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopFollow> ShopFollow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopPackage> ShopPackage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopPaymentType> ShopPaymentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopPicture> ShopPicture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopProductType> ShopProductType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopReportBlock> ShopReportBlock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopReseller> ShopReseller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopUser> ShopUser { get; set; }
    }
}
