//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopChat
    {
        public int ID { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> ShopId { get; set; }
        public string Body { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public Nullable<bool> IsAccountSend { get; set; }
        public Nullable<bool> IsRead { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
