//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopReseller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShopReseller()
        {
            this.AccountBasket = new HashSet<AccountBasket>();
            this.AccountOrderProduct = new HashSet<AccountOrderProduct>();
            this.ShopResellerCollection = new HashSet<ShopResellerCollection>();
            this.ShopResellerGallery = new HashSet<ShopResellerGallery>();
            this.ShopResellerLanguage = new HashSet<ShopResellerLanguage>();
            this.ShopResellerProduct = new HashSet<ShopResellerProduct>();
            this.ShopResellerStory = new HashSet<ShopResellerStory>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> PictureId { get; set; }
        public Nullable<int> CoverPictureId { get; set; }
        public Nullable<int> PersonalPictureId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Name { get; set; }
        public Nullable<int> BenefitPercent { get; set; }
        public string AddressValue { get; set; }
        public string Manager { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountBasket> AccountBasket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountOrderProduct> AccountOrderProduct { get; set; }
        public virtual City City { get; set; }
        public virtual Picture Picture { get; set; }
        public virtual Picture Picture1 { get; set; }
        public virtual Picture Picture2 { get; set; }
        public virtual Shop Shop { get; set; }
        public virtual SiteUser SiteUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopResellerCollection> ShopResellerCollection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopResellerGallery> ShopResellerGallery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopResellerLanguage> ShopResellerLanguage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopResellerProduct> ShopResellerProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopResellerStory> ShopResellerStory { get; set; }
    }
}
