//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Slider()
        {
            this.SliderLanguage = new HashSet<SliderLanguage>();
        }
    
        public int ID { get; set; }
        public Nullable<int> WebsiteId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> PictureId { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public Nullable<int> ShowNumber { get; set; }
        public string SecondName { get; set; }
        public Nullable<int> FileId { get; set; }
    
        public virtual Picture Picture { get; set; }
        public virtual SiteUser SiteUser { get; set; }
        public virtual Website Website { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SliderLanguage> SliderLanguage { get; set; }
    }
}
