//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreCompetitiveFeature
    {
        public int ID { get; set; }
        public int CompetitiveFeatureId { get; set; }
        public int StoreId { get; set; }
    
        public virtual CompetitiveFeature CompetitiveFeature { get; set; }
        public virtual Store Store { get; set; }
    }
}
