//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SurveyQuestion()
        {
            this.SurveyAnswerDetail = new HashSet<SurveyAnswerDetail>();
            this.SurveyQuestionItem = new HashSet<SurveyQuestionItem>();
            this.SurveyQuestionLanguage = new HashSet<SurveyQuestionLanguage>();
        }
    
        public int ID { get; set; }
        public string Question { get; set; }
        public Nullable<int> QuestionType { get; set; }
        public Nullable<int> SurveyId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> ShowNumber { get; set; }
    
        public virtual Code Code { get; set; }
        public virtual Survey Survey { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyAnswerDetail> SurveyAnswerDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyQuestionItem> SurveyQuestionItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyQuestionLanguage> SurveyQuestionLanguage { get; set; }
    }
}
