//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warranty
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Serial { get; set; }
        public string Config { get; set; }
        public string Date { get; set; }
    }
}
