//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteUser
    {
        public int ID { get; set; }
        public int WebsiteId { get; set; }
        public int UserId { get; set; }
    
        public virtual SiteUser SiteUser { get; set; }
        public virtual Website Website { get; set; }
    }
}
