//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebsiteForm()
        {
            this.WebsiteFormAccount = new HashSet<WebsiteFormAccount>();
            this.WebsiteFormField = new HashSet<WebsiteFormField>();
        }
    
        public int ID { get; set; }
        public int WebsiteId { get; set; }
        public int UserCreatorId { get; set; }
        public string Name { get; set; }
        public string Label { get; set; }
    
        public virtual SiteUser SiteUser { get; set; }
        public virtual Website Website { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebsiteFormAccount> WebsiteFormAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebsiteFormField> WebsiteFormField { get; set; }
    }
}
