//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteFormValue
    {
        public int ID { get; set; }
        public Nullable<int> AccountId { get; set; }
        public int FieldId { get; set; }
        public Nullable<int> AccountFormId { get; set; }
        public string Value { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual WebsiteFormAccount WebsiteFormAccount { get; set; }
        public virtual WebsiteFormField WebsiteFormField { get; set; }
    }
}
