//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Services.OnlinePayments.NextPay {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="payment.soap", ConfigurationName="Services.OnlinePayments.NextPay.Application")]
    public interface Application {
        
        // CODEGEN: Generating message contract since the operation PaymentVerification is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="PaymentVerification", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataLayer.Services.OnlinePayments.NextPay.PaymentVerificationResponse1 PaymentVerification(DataLayer.Services.OnlinePayments.NextPay.PaymentVerification1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="PaymentVerification", ReplyAction="*")]
        System.Threading.Tasks.Task<DataLayer.Services.OnlinePayments.NextPay.PaymentVerificationResponse1> PaymentVerificationAsync(DataLayer.Services.OnlinePayments.NextPay.PaymentVerification1 request);
        
        // CODEGEN: Generating message contract since the operation TokenGenerator is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="TokenGenerator", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataLayer.Services.OnlinePayments.NextPay.TokenGeneratorResponse1 TokenGenerator(DataLayer.Services.OnlinePayments.NextPay.TokenGenerator1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="TokenGenerator", ReplyAction="*")]
        System.Threading.Tasks.Task<DataLayer.Services.OnlinePayments.NextPay.TokenGeneratorResponse1> TokenGeneratorAsync(DataLayer.Services.OnlinePayments.NextPay.TokenGenerator1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="payment.soap")]
    public partial class PaymentVerification : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string api_keyField;
        
        private string order_idField;
        
        private string amountField;
        
        private string trans_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string api_key {
            get {
                return this.api_keyField;
            }
            set {
                this.api_keyField = value;
                this.RaisePropertyChanged("api_key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string order_id {
            get {
                return this.order_idField;
            }
            set {
                this.order_idField = value;
                this.RaisePropertyChanged("order_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=2)]
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string trans_id {
            get {
                return this.trans_idField;
            }
            set {
                this.trans_idField = value;
                this.RaisePropertyChanged("trans_id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Token")]
    public partial class Token : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string trans_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string trans_id {
            get {
                return this.trans_idField;
            }
            set {
                this.trans_idField = value;
                this.RaisePropertyChanged("trans_id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="payment.soap")]
    public partial class TokenGeneratorResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Token tokenGeneratorResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public Token TokenGeneratorResult {
            get {
                return this.tokenGeneratorResultField;
            }
            set {
                this.tokenGeneratorResultField = value;
                this.RaisePropertyChanged("TokenGeneratorResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="payment.soap")]
    public partial class TokenGenerator : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string api_keyField;
        
        private string order_idField;
        
        private string amountField;
        
        private string callback_uriField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string api_key {
            get {
                return this.api_keyField;
            }
            set {
                this.api_keyField = value;
                this.RaisePropertyChanged("api_key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string order_id {
            get {
                return this.order_idField;
            }
            set {
                this.order_idField = value;
                this.RaisePropertyChanged("order_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=2)]
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string callback_uri {
            get {
                return this.callback_uriField;
            }
            set {
                this.callback_uriField = value;
                this.RaisePropertyChanged("callback_uri");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Verify")]
    public partial class Verify : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        private string card_holderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string card_holder {
            get {
                return this.card_holderField;
            }
            set {
                this.card_holderField = value;
                this.RaisePropertyChanged("card_holder");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="payment.soap")]
    public partial class PaymentVerificationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Verify paymentVerificationResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public Verify PaymentVerificationResult {
            get {
                return this.paymentVerificationResultField;
            }
            set {
                this.paymentVerificationResultField = value;
                this.RaisePropertyChanged("PaymentVerificationResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaymentVerification1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="payment.soap", Order=0)]
        public DataLayer.Services.OnlinePayments.NextPay.PaymentVerification PaymentVerification;
        
        public PaymentVerification1() {
        }
        
        public PaymentVerification1(DataLayer.Services.OnlinePayments.NextPay.PaymentVerification PaymentVerification) {
            this.PaymentVerification = PaymentVerification;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaymentVerificationResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="payment.soap", Order=0)]
        public DataLayer.Services.OnlinePayments.NextPay.PaymentVerificationResponse PaymentVerificationResponse;
        
        public PaymentVerificationResponse1() {
        }
        
        public PaymentVerificationResponse1(DataLayer.Services.OnlinePayments.NextPay.PaymentVerificationResponse PaymentVerificationResponse) {
            this.PaymentVerificationResponse = PaymentVerificationResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TokenGenerator1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="payment.soap", Order=0)]
        public DataLayer.Services.OnlinePayments.NextPay.TokenGenerator TokenGenerator;
        
        public TokenGenerator1() {
        }
        
        public TokenGenerator1(DataLayer.Services.OnlinePayments.NextPay.TokenGenerator TokenGenerator) {
            this.TokenGenerator = TokenGenerator;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TokenGeneratorResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="payment.soap", Order=0)]
        public DataLayer.Services.OnlinePayments.NextPay.TokenGeneratorResponse TokenGeneratorResponse;
        
        public TokenGeneratorResponse1() {
        }
        
        public TokenGeneratorResponse1(DataLayer.Services.OnlinePayments.NextPay.TokenGeneratorResponse TokenGeneratorResponse) {
            this.TokenGeneratorResponse = TokenGeneratorResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ApplicationChannel : DataLayer.Services.OnlinePayments.NextPay.Application, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApplicationClient : System.ServiceModel.ClientBase<DataLayer.Services.OnlinePayments.NextPay.Application>, DataLayer.Services.OnlinePayments.NextPay.Application {
        
        public ApplicationClient() {
        }
        
        public ApplicationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApplicationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataLayer.Services.OnlinePayments.NextPay.PaymentVerificationResponse1 DataLayer.Services.OnlinePayments.NextPay.Application.PaymentVerification(DataLayer.Services.OnlinePayments.NextPay.PaymentVerification1 request) {
            return base.Channel.PaymentVerification(request);
        }
        
        public DataLayer.Services.OnlinePayments.NextPay.PaymentVerificationResponse PaymentVerification(DataLayer.Services.OnlinePayments.NextPay.PaymentVerification PaymentVerification1) {
            DataLayer.Services.OnlinePayments.NextPay.PaymentVerification1 inValue = new DataLayer.Services.OnlinePayments.NextPay.PaymentVerification1();
            inValue.PaymentVerification = PaymentVerification1;
            DataLayer.Services.OnlinePayments.NextPay.PaymentVerificationResponse1 retVal = ((DataLayer.Services.OnlinePayments.NextPay.Application)(this)).PaymentVerification(inValue);
            return retVal.PaymentVerificationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataLayer.Services.OnlinePayments.NextPay.PaymentVerificationResponse1> DataLayer.Services.OnlinePayments.NextPay.Application.PaymentVerificationAsync(DataLayer.Services.OnlinePayments.NextPay.PaymentVerification1 request) {
            return base.Channel.PaymentVerificationAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataLayer.Services.OnlinePayments.NextPay.PaymentVerificationResponse1> PaymentVerificationAsync(DataLayer.Services.OnlinePayments.NextPay.PaymentVerification PaymentVerification) {
            DataLayer.Services.OnlinePayments.NextPay.PaymentVerification1 inValue = new DataLayer.Services.OnlinePayments.NextPay.PaymentVerification1();
            inValue.PaymentVerification = PaymentVerification;
            return ((DataLayer.Services.OnlinePayments.NextPay.Application)(this)).PaymentVerificationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataLayer.Services.OnlinePayments.NextPay.TokenGeneratorResponse1 DataLayer.Services.OnlinePayments.NextPay.Application.TokenGenerator(DataLayer.Services.OnlinePayments.NextPay.TokenGenerator1 request) {
            return base.Channel.TokenGenerator(request);
        }
        
        public DataLayer.Services.OnlinePayments.NextPay.TokenGeneratorResponse TokenGenerator(DataLayer.Services.OnlinePayments.NextPay.TokenGenerator TokenGenerator1) {
            DataLayer.Services.OnlinePayments.NextPay.TokenGenerator1 inValue = new DataLayer.Services.OnlinePayments.NextPay.TokenGenerator1();
            inValue.TokenGenerator = TokenGenerator1;
            DataLayer.Services.OnlinePayments.NextPay.TokenGeneratorResponse1 retVal = ((DataLayer.Services.OnlinePayments.NextPay.Application)(this)).TokenGenerator(inValue);
            return retVal.TokenGeneratorResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataLayer.Services.OnlinePayments.NextPay.TokenGeneratorResponse1> DataLayer.Services.OnlinePayments.NextPay.Application.TokenGeneratorAsync(DataLayer.Services.OnlinePayments.NextPay.TokenGenerator1 request) {
            return base.Channel.TokenGeneratorAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataLayer.Services.OnlinePayments.NextPay.TokenGeneratorResponse1> TokenGeneratorAsync(DataLayer.Services.OnlinePayments.NextPay.TokenGenerator TokenGenerator) {
            DataLayer.Services.OnlinePayments.NextPay.TokenGenerator1 inValue = new DataLayer.Services.OnlinePayments.NextPay.TokenGenerator1();
            inValue.TokenGenerator = TokenGenerator;
            return ((DataLayer.Services.OnlinePayments.NextPay.Application)(this)).TokenGeneratorAsync(inValue);
        }
    }
}
