using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DataLayer.Enumarables
{
    public enum Enum_Permission
    {
        User,
        UserGroup,
        UserGroup_Details,
        UserGroup_New,
        UserGroup_Edit,
        UserGroup_Delete,
        QuestionProduct,
        QuestionProduct_New,
        QuestionProduct_Edit,
        QuestionProduct_Delete,
        UserGroup_Permission,
        UserGroup_Users,
        SiteUser,
        SiteUser_Details,
        SiteUser_New,
        SiteUser_Edit,
        SiteUser_Delete,
        SiteUser_Password,
        SiteUser_Groups,
        SiteUserShop,
        SiteUserShop_Edit,
        SiteUserShop_NewPassword,
        SiteUserShop_ChangePassword,


        Content,
        Menu,
        Menu_Details,
        Menu_New,
        Menu_Edit,
        Menu_Delete,
        QuestionSmartOffer,
        QuestionSmartOffer_New,
        QuestionSmartOffer_Edit,
        QuestionSmartOffer_Delete,
        Category,
        Category_Details,
        Category_New,
        Category_Edit,
        Category_Delete,

        Post,
        Post_Details,
        Post_New,
        Post_Edit,
        Post_Delete,
        State,
        State_Details,
        State_New,
        State_Edit,
        State_Delete,
        City,
        City_Details,
        City_New,
        City_Edit,
        City_Delete,
        Gallery,
        Gallery_Details,
        Gallery_New,
        Gallery_Edit,
        Gallery_Delete,


        WebsiteContactForm,
        WebsiteContactForm_Details,

        Slider,
        Slider_New,
        Slider_Edit,
        Slider_Delete,
        Slider_Details,

        WebsiteForm,
        WebsiteForm_New,
        WebsiteForm_Edit,
        WebsiteForm_Delete,
        WebsiteForm_Details,

        Banner,
        Banner_New,
        Banner_Edit,
        Banner_Delete,
        Banner_Details,
        DashboardFiles,
        DashboardFiles_New,
        DashboardFiles_Edit,
        DashboardFiles_Delete,
        DashboardFiles_Details,
        
        StaticPage,
        StaticPage_New,
        StaticPage_Edit,
        StaticPage_Delete,

        WebsiteDetail,
        WebsiteDetail_Edit,

        ContactUs,
        ContactUs_Details,

        Setting,
        Domain,
        Language,
        Module,
        Permission,

        Language_New,
        Language_Edit,
        Language_Delete,
        Language_Details,

        EmailHost,
        EmailHost_New,
        EmailHost_Edit,
        EmailHost_Delete,
        EmailHost_Details,
        SmsSetting,
        SmsSetting_New,
        SmsSetting_Edit,
        SmsSetting_Delete,
        SmsSetting_Details,
        Website,
        Website_New,
        Website_Edit,
        Website_Delete,
        Website_Details,
        WebsiteDomain,
        WebsiteDomain_New,
        WebsiteDomain_Edit,
        WebsiteDomain_Delete,
        WebsiteDomain_Details,
        Template,
        Template_New,
        Template_Edit,
        Template_Delete,
        Template_Details,
        Agreement,
        Agreement_Details,
        Agreement_New,
        Agreement_Edit,
        Agreement_Delete,

        NotificationProject,
        NotificationProject_Details,
        NotificationProject_New,
        NotificationProject_Edit,
        NotificationProject_Delete,

        Dashboard,

        Mall,
        Mall_New,
        Mall_Edit,
        Mall_Delete,
        Mall_Details,

        Shop,
        Shop_New,
        Shop_Edit,
        Shop_Details,
        Shop_Delete,
        Shop_Profile,
        Shop_Follow,
        Shop_Chat,
        Shop_PriceUnit,

        Store,
        Store_New,
        Store_Edit,
        Store_Delete,
        Store_Details,
       
        StoreProduct,
        StoreProduct_Edit,

        ShopReseller,
        ShopReseller_New,
        ShopReseller_Edit,
        ShopReseller_Details,
        ShopReseller_Delete,

        ProductType,
        ProductType_New,
        ProductType_Edit,
        ProductType_Delete,
        ProductType_Details,

        ProductCategory,
        ProductCategory_New,
        ProductCategory_Edit,
        ProductCategory_Delete,
        ProductCategory_Details,

        ProductSubCategory,
        ProductSubCategory_New,
        ProductSubCategory_Edit,
        ProductSubCategory_Delete,
        ProductSubCategory_Details,

        ProductComment,
        ProductComment_Answer,
        ProductComment_Details,
        ProductComment_Delete,
        CreditShoping,
        CreditShoping_Answer,
        Color,
        Color_New,
        Color_Edit,
        Color_Delete,
        Color_Details,
        ShippingSubscription,
        ShippingSubscription_New,
        ShippingSubscription_Edit,
        ShippingSubscription_Delete,
        ShippingSubscription_Details,
        Size,
        Size_New,
        Size_Edit,
        Size_Delete,
        Size_Details,
        
        Product,
        Product_New,
        Product_Edit,
        Product_Delete,
        Product_Details,
        Advertising,
        Advertising_New,
        Advertising_Edit,
        Advertising_Delete,
        ShopUser,
        ShopUser_Details,
        ShopUser_New,
        ShopUser_Edit,
        ShopUser_Delete,

        ProductCustomField,
        ProductCustomField_New,
        ProductCustomField_Edit,
        ProductCustomField_Delete,
        ProductCustomField_Details,

        ProductCustomFieldItem,
        ProductCustomFieldItem_New,
        ProductCustomFieldItem_Edit,
        ProductCustomFieldItem_Delete,
        ProductCustomFieldItem_Details,

        ProductOption,
        ProductOption_New,
        ProductOption_Edit,
        ProductOption_Delete,
        ProductOption_Details,

        ProductBrand,
        ProductBrand_New,
        ProductBrand_Edit,
        ProductBrand_Delete,
        ProductBrand_Details,

        ProductCategoryCompany,
        ProductCategoryCompany_New,
        ProductCategoryCompany_Edit,
        ProductCategoryCompany_Delete,
        ProductCategoryCompany_Details,

        ProductCompany,
        ProductCompany_New,
        ProductCompany_Edit,
        ProductCompany_Delete,
        ProductCompany_Details,

        ShopContact,
        ShopContact_Details,
        ShopContact_New,
        ShopContact_Edit,
        ShopContact_Delete,

        DiscountGroup,
        DiscountGroup_Details,
        DiscountGroup_New,
        DiscountGroup_Edit,
        DiscountGroup_Delete,

        Discount,
        Discount_New,
        Discount_Edit,
        Discount_Delete,
        Discount_Details,

        Rebate,
        Rebate_New,
        Rebate_Edit,
        Rebate_Details,
        Rebate_Delete,

        Package,
        Package_New,
        Package_Edit,
        Package_Details,
        Package_Delete,

        Financial,
        Merchant,
        Merchant_New,
        Merchant_Edit,
        Merchant_Delete,
        Merchant_Details,

        Currency,
        Currency_Create,
        Currency_Edit,
        Currency_Detail,
        Crrency_Delete,


        Crm,
        Account,
        Account_New,
        Account_Edit,
        Account_Delete,
        Account_Details,

        AccountOrder,
        AccountOrder_Details,
        AccountLadder,
        AccountLadder_Details,
        NewsletterGroup,
        NewsletterGroup_New,
        NewsletterGroup_Edit,
        NewsletterGroup_Details,
        NewsletterGroup_Delete,
        NewsletterGroup_Sms,
        NewsletterGroup_Email,
        NewsletterGroup_Items,

        TelegramBot,
        TelegramBot_New,
        TelegramBot_Edit,
        TelegramBot_Delete,
        TelegramBot_Details,
        TelegramBot_Account,
        TelegramBot_Command,
        TelegramBot_Keyboard,
        TelegramBot_Group,
        TelegramBot_Channel,

        Report,
        Report_ShopReseller,
        Report_Rebate,
        Report_SaleMonth,

        Clearing,
        Clearing_New,
        Clearing_Edit,

        OnineOrder,
        CompetitiveFeature,
        CompetitiveFeature_New,
        CompetitiveFeature_Edit,
        CompetitiveFeature_Delete,
        CompetitiveFeature_Details,
        SendSMS,
        SendSMS_New,
        SendSMS_Edit,
        SendSMS_Delete,
        SendSMS_Details,
        Survey,
        StoreComment,
        StoreComment_Details,
        StoreComment_Answer,
        StoreComment_Delete,
        Warranty,
        Warranty_New,
        Warranty_Edit,
        Warranty_Delete,
        Question,
        Question_New,
        Question_Edit,
        Question_Delete,
    }
}
