using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DataLayer.Enumarables
{
    public enum Enum_Code
    {
        MENU_TYPE_LINK,
        MENU_TYPE_POST,
        MENU_TYPE_CATEGORY,
        MENU_TYPE_GALLERY,
        

        Order_Register,
        Order_Track,
        Order_End,
        CATEGORY_TYPE_GALLERY,
        CATEGORY_TYPE_CONTENT,
        CATEGORY_TYPE_BANNER,

        EMAIL_STATUS_INBOX,
        EMAIL_STATUS_IMPORTANT,
        EMAIL_STATUS_SENT,
        EMAIL_STATUS_DRAFT,
        EMAIL_STATUS_TRASH,

        SYSTEM_TYPE_PANEL,
        SYSTEM_TYPE_WEBSITE,
        SYSTEM_TYPE_CMS,
        SYSTEM_TYPE_SOCIAL,
        SYSTEM_TYPE_API,
        SYSTEM_TYPE_SYNCSERVER,
        SYSTEM_TYPE_OAUTH,
        SYSTEM_TYPE_LOCAL,
        SYSTEM_TYPE_SHOP,

        FIELD_TYPE_STRING,
        FIELD_TYPE_INTEGER,
        FIELD_TYPE_DATE,
        FIELD_TYPE_TEXT,
        FIELD_TYPE_HTML,
        FIELD_TYPE_FILE,
        FIELD_TYPE_DROPDOWN,
        FIELD_TYPE_BOOLEAN,
        FIELD_TYPE_RADIOBUTTON,

        PRODUCT_STATUS_AVAILABLE,
        PRODUCT_STATUS_SOON,
        PRODUCT_STATUS_NOT_AVAILABLE,
        PRODUCT_STATUS_NOT_SELLING,

        CONTACT_TYPE_PHONE,
        CONTACT_TYPE_MOBILE,
        CONTACT_TYPE_WEBSITE,
        CONTACT_TYPE_TELEGRAM,
        CONTACT_TYPE_INSTAGRAM,
        CONTACT_TYPE_FAX,
        CONTACT_TYPE_EMAIL,
        CONTACT_TYPE_WHATSAPP,
        CONTACT_TYPE_WECHAT,
        CONTACT_TYPE_LINKEDIN,
        CONTACT_TYPE_ADDRESS,
        CONTACT_TYPE_POSTAL_CODE,

        DISCOUNTGROUP_NONE,
        DISCOUNTGROUP_TYPE_PRICE,
        DISCOUNTGROUP_TYPE_PERCENT,

        DISCOUNT_TYPE_NONE,
        DISCOUNT_TYPE_SHOP,
        DISCOUNT_TYPE_PRODUCTTYPE,
        DISCOUNT_TYPE_CATEGORY,
        DISCOUNT_TYPE_SUBCATEGORY,
        DISCOUNT_TYPE_PRODUCT,
        DISCOUNT_TYPE_BRAND,
        DISCOUNT_TYPE_VARIENTY,

        LANGUAGE_DIRECTION_RTL,
        LANGUAGE_DIRECTION_LTR,

        PLATFORM_TYPE_WEB,
        PLATFORM_TYPE_ANDROID,
        PLATFORM_TYPE_IOS,
        PLATFORM_TYPE_WINDOWS,

        SHOP_TYPE_INTERNAL,
        SHOP_TYPE_IMPORTER,
        SHOP_TYPE_EXPORTER,


        ORDER_STATUS_INSERTED,
        ORDER_STATUS_ADDRESS,
        ORDER_STATUS_SUCCESS,
        ORDER_STATUS_PROCESS,
        ORDER_STATUS_STORE,
        ORDER_STATUS_POST,
        ORDER_STATUS_CANCEL,
        ORDER_STATUS_ARCHIVES,

        PAYMENT_STATUS_INSERTED,
        PAYMENT_STATUS_STARTED,
        PAYMENT_STATUS_START_ERROR,
        PAYMENT_STATUS_VERIFY,
        PAYMENT_STATUS_VERIFY_ERROR,
        PAYMENT_STATUS_SERVICE_FAILED,
        PAYMENT_STATUS_SUCCESSFUL,

        NOTIFICATION_SENDER_FIREBASE,
        NOTIFICATION_SENDER_ONESIGNAL,

        ACCOUNT_TYPE_REAL,
        ACCOUNT_TYPE_LEGAL,

        TELEGRAM_COMMAND_TYPE_TEXT,
        TELEGRAM_COMMAND_TYPE_PICTURE,
        TELEGRAM_COMMAND_TYPE_VOICE,
        TELEGRAM_COMMAND_TYPE_VIDEO,
        TELEGRAM_COMMAND_TYPE_KEYBOARD,
        TELEGRAM_COMMAND_TYPE_SURVEY,

        TELEGRAM_KEYBOARD_TYPE_BUTTON,
        TELEGRAM_KEYBOARD_TYPE_GLASS,

        REBATE_TYPE_SHOP,
        REBATE_TYPE_PRODUCTTYPE,
        REBATE_TYPE_PRODUCTCATEGORY,
        REBATE_TYPE_PRODUCTSUBCATEGORY,
        REBATE_TYPE_PRODUCTBRAND,

        STOREPRODUCT_REQUEST_NOT_CHECKED,
        STOREPRODUCT_REQUEST_APPROVED,
        STOREPRODUCT_REQUEST_REJECTED,

        CLEARING_TYPE_ONLINE_ORDER,
        CLEARING_TYPE_OTHER,

        IRR,
        AFN,
        USD,
        EUR,
        ORDER_STATUS_NONE,
        Product_Category,
    }
}
